In [19]:
import os
import json
import pickle
import datetime

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score, classification_report

from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.applications import MobileNetV2, EfficientNetB0
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocess

In [20]:
SEEDS = [42, 123, 2024, 3407, 777]

BATCH_SIZE = 32
EPOCHS = 50
PATIENCE = 5
LEARNING_RATE = 1e-5
FINE_TUNE_LAYERS = 20
AUTOTUNE = tf.data.AUTOTUNE

CANONICAL_CLASSES = ["Early Blight", "Late Blight", "Healthy"]
NUM_CLASSES = len(CANONICAL_CLASSES)

SOURCE_DATASET_DIR = "/kaggle/input/datasets/faysalmiah1721758/potato-dataset"
TARGET_DATASET_DIR = "/kaggle/input/datasets/shahadhossin567r7455/potato-leaf-disease-dataset/Potato Leaf DIsease"

RUN_TIMESTAMP = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
OUTPUT_DIR = f"cross_dataset_transfer_{RUN_TIMESTAMP}"

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(os.path.join(OUTPUT_DIR, "models"), exist_ok=True)
os.makedirs(os.path.join(OUTPUT_DIR, "histories"), exist_ok=True)
os.makedirs(os.path.join(OUTPUT_DIR, "reports"), exist_ok=True)

print("Output directory:", OUTPUT_DIR)

Output directory: cross_dataset_transfer_20260530-210441

In [21]:
CLASS_FOLDER_CANDIDATES = {
    "Early Blight": [
        "Early Blight",
        "Early_Blight",
        "Potato___Early_blight",
        "Potato___Early_Blight"
    ],
    "Late Blight": [
        "Late Blight",
        "Late_Blight",
        "Potato___Late_blight",
        "Potato___Late_Blight"
    ],
    "Healthy": [
        "Healthy",
        "healthy",
        "Potato___healthy",
        "Potato___Healthy"
    ]
}


def find_class_folder(dataset_dir, canonical_class):
    available_folders = [
        folder for folder in os.listdir(dataset_dir)
        if os.path.isdir(os.path.join(dataset_dir, folder))
    ]

    for candidate in CLASS_FOLDER_CANDIDATES[canonical_class]:
        if candidate in available_folders:
            return os.path.join(dataset_dir, candidate)

    raise ValueError(
        f"Could not find folder for class '{canonical_class}' in {dataset_dir}. "
        f"Available folders: {available_folders}"
    )


def collect_paths_and_labels(dataset_dir):
    valid_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

    file_paths = []
    labels = []

    for label_index, class_name in enumerate(CANONICAL_CLASSES):
        class_dir = find_class_folder(dataset_dir, class_name)

        for fname in os.listdir(class_dir):
            if fname.lower().endswith(valid_extensions):
                file_paths.append(os.path.join(class_dir, fname))
                labels.append(label_index)

    file_paths = np.array(file_paths)
    labels = np.array(labels)

    print("\nDataset:", dataset_dir)
    print("Total images:", len(labels))

    unique, counts = np.unique(labels, return_counts=True)
    for idx, count in zip(unique, counts):
        print(f"{CANONICAL_CLASSES[idx]}: {count}")

    return file_paths, labels

In [22]:
source_paths, source_labels = collect_paths_and_labels(SOURCE_DATASET_DIR)
target_paths, target_labels = collect_paths_and_labels(TARGET_DATASET_DIR)

Dataset: /kaggle/input/datasets/faysalmiah1721758/potato-dataset
Total images: 2152
Early Blight: 1000
Late Blight: 1000
Healthy: 152

Dataset: /kaggle/input/datasets/shahadhossin567r7455/potato-leaf-disease-dataset/Potato Leaf DIsease
Total images: 1500
Early Blight: 500
Late Blight: 500
Healthy: 500

In [23]:
def make_splits(file_paths, labels, seed):
    X_train, X_temp, y_train, y_temp = train_test_split(
        file_paths,
        labels,
        test_size=0.20,
        stratify=labels,
        random_state=seed
    )

    X_val, X_test, y_val, y_test = train_test_split(
        X_temp,
        y_temp,
        test_size=0.50,
        stratify=y_temp,
        random_state=seed
    )

    return X_train, X_val, X_test, y_train, y_val, y_test

In [24]:
def load_tf_dataset(file_paths, labels, image_size, preprocess_fn, augment=False, shuffle=True, seed=None):
    ds = tf.data.Dataset.from_tensor_slices((file_paths, labels))

    def process(path, label):
        image = tf.io.read_file(path)
        image = tf.image.decode_image(image, channels=3, expand_animations=False)
        image.set_shape([None, None, 3])

        image = tf.image.resize(image, image_size)
        image = tf.cast(image, tf.float32)

        if augment:
            image = tf.image.random_flip_left_right(image)
            image = tf.image.random_brightness(image, max_delta=25.5)
            image = tf.image.random_contrast(image, lower=0.9, upper=1.1)
            image = tf.clip_by_value(image, 0.0, 255.0)

        image = preprocess_fn(image)
        label = tf.one_hot(label, depth=NUM_CLASSES)

        return image, label

    ds = ds.map(process, num_parallel_calls=AUTOTUNE)

    if shuffle:
        ds = ds.shuffle(
            buffer_size=len(file_paths),
            seed=seed,
            reshuffle_each_iteration=True
        )

    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

    return ds

In [25]:
def cnn_preprocess(image):
    return image / 255.0


MODEL_CONFIGS = {
    "Lightweight CNN": {
        "image_size": (256, 256),
        "preprocess_fn": cnn_preprocess
    },
    "MobileNetV2": {
        "image_size": (224, 224),
        "preprocess_fn": mobilenet_preprocess
    },
    "EfficientNetB0": {
        "image_size": (224, 224),
        "preprocess_fn": efficientnet_preprocess
    }
}

In [26]:
def build_improved_cnn(input_shape=(256, 256, 3), num_classes=3):
    inputs = tf.keras.Input(shape=input_shape)

    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(128, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(128, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Flatten()(x)
    x = layers.Dense(128, activation='relu')(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = tf.keras.Model(inputs=inputs, outputs=outputs, name="LightweightCNN")
    return model


def build_mobilenet_v2(input_shape=(224, 224, 3), num_classes=3):
    inputs = tf.keras.Input(shape=input_shape)

    backbone = MobileNetV2(
        include_top=False,
        weights="imagenet",
        input_tensor=inputs
    )

    backbone.trainable = True

    for layer in backbone.layers[:-FINE_TUNE_LAYERS]:
        layer.trainable = False

    x = backbone.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return tf.keras.Model(inputs=inputs, outputs=outputs, name="MobileNetV2_transfer")


def build_efficientnet_b0(input_shape=(224, 224, 3), num_classes=3):
    inputs = tf.keras.Input(shape=input_shape)

    backbone = EfficientNetB0(
        include_top=False,
        weights="imagenet",
        input_tensor=inputs
    )

    backbone.trainable = True

    for layer in backbone.layers[:-FINE_TUNE_LAYERS]:
        layer.trainable = False

    x = backbone.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return tf.keras.Model(inputs=inputs, outputs=outputs, name="EfficientNetB0_transfer")


MODEL_BUILDERS = {
    "Lightweight CNN": build_improved_cnn,
    "MobileNetV2": build_mobilenet_v2,
    "EfficientNetB0": build_efficientnet_b0
}

In [27]:
def get_class_weights(y_train):
    class_weight_vals = compute_class_weight(
        class_weight="balanced",
        classes=np.arange(NUM_CLASSES),
        y=y_train
    )

    return dict(enumerate(class_weight_vals))

In [28]:
def run_cross_dataset_experiment(model_name, seed):
    print("\n" + "=" * 80)
    print(f"Model: {model_name} | Seed: {seed}")
    print("=" * 80)

    tf.keras.backend.clear_session()
    tf.keras.utils.set_random_seed(seed)

    image_size = MODEL_CONFIGS[model_name]["image_size"]
    preprocess_fn = MODEL_CONFIGS[model_name]["preprocess_fn"]

    source_train, source_val, source_test, y_source_train, y_source_val, y_source_test = make_splits(
        source_paths,
        source_labels,
        seed
    )

    target_train, target_val, target_test, y_target_train, y_target_val, y_target_test = make_splits(
        target_paths,
        target_labels,
        seed
    )

    source_train_ds = load_tf_dataset(source_train, y_source_train, image_size, preprocess_fn, augment=True, shuffle=True, seed=seed)
    source_val_ds = load_tf_dataset(source_val, y_source_val, image_size, preprocess_fn, augment=False, shuffle=False)
    source_test_ds = load_tf_dataset(source_test, y_source_test, image_size, preprocess_fn, augment=False, shuffle=False)

    target_train_ds = load_tf_dataset(target_train, y_target_train, image_size, preprocess_fn, augment=True, shuffle=True, seed=seed)
    target_val_ds = load_tf_dataset(target_val, y_target_val, image_size, preprocess_fn, augment=False, shuffle=False)
    target_test_ds = load_tf_dataset(target_test, y_target_test, image_size, preprocess_fn, augment=False, shuffle=False)

    model = MODEL_BUILDERS[model_name](
        input_shape=(image_size[0], image_size[1], 3),
        num_classes=NUM_CLASSES
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    safe_model_name = model_name.replace(" ", "_")
    run_name = f"{safe_model_name}_seed_{seed}"

    source_model_path = os.path.join(OUTPUT_DIR, "models", f"{run_name}_source.keras")
    finetuned_model_path = os.path.join(OUTPUT_DIR, "models", f"{run_name}_target_finetuned.keras")

    source_history_path = os.path.join(OUTPUT_DIR, "histories", f"{run_name}_source_history.pkl")
    target_history_path = os.path.join(OUTPUT_DIR, "histories", f"{run_name}_target_finetune_history.pkl")

    source_callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=PATIENCE,
            restore_best_weights=True
        ),
        ModelCheckpoint(
            source_model_path,
            monitor="val_loss",
            save_best_only=True
        )
    ]

    source_history = model.fit(
        source_train_ds,
        validation_data=source_val_ds,
        epochs=EPOCHS,
        callbacks=source_callbacks,
        class_weight=get_class_weights(y_source_train),
        verbose=1
    )

    with open(source_history_path, "wb") as f:
        pickle.dump(source_history.history, f)

    source_eval = evaluate_model(model, source_test_ds)
    zero_shot_eval = evaluate_model(model, target_test_ds)

    target_callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=PATIENCE,
            restore_best_weights=True
        ),
        ModelCheckpoint(
            finetuned_model_path,
            monitor="val_loss",
            save_best_only=True
        )
    ]

    target_history = model.fit(
        target_train_ds,
        validation_data=target_val_ds,
        epochs=EPOCHS,
        callbacks=target_callbacks,
        class_weight=get_class_weights(y_target_train),
        verbose=1
    )

    with open(target_history_path, "wb") as f:
        pickle.dump(target_history.history, f)

    finetuned_eval = evaluate_model(model, target_test_ds)

    source_acc = source_eval["accuracy"]
    zero_acc = zero_shot_eval["accuracy"]
    fine_acc = finetuned_eval["accuracy"]

    result = {
        "model": model_name,
        "seed": seed,

        "source_loss": source_eval["loss"],
        "source_accuracy": source_acc,
        "source_macro_f1": source_eval["macro_f1"],
        "source_weighted_f1": source_eval["weighted_f1"],

        "zero_shot_loss": zero_shot_eval["loss"],
        "zero_shot_accuracy": zero_acc,
        "zero_shot_macro_f1": zero_shot_eval["macro_f1"],
        "zero_shot_weighted_f1": zero_shot_eval["weighted_f1"],

        "finetuned_loss": finetuned_eval["loss"],
        "finetuned_accuracy": fine_acc,
        "finetuned_macro_f1": finetuned_eval["macro_f1"],
        "finetuned_weighted_f1": finetuned_eval["weighted_f1"],

        "zero_shot_drop": source_acc - zero_acc,
        "finetuned_drop": source_acc - fine_acc,
        "zero_shot_ratio": zero_acc / source_acc if source_acc > 0 else np.nan,
        "finetuned_ratio": fine_acc / source_acc if source_acc > 0 else np.nan,

        "source_model_path": source_model_path,
        "finetuned_model_path": finetuned_model_path,
        "source_history_path": source_history_path,
        "target_history_path": target_history_path
    }

    print("\nResult:")
    print(result)

    return result

In [30]:
from sklearn.metrics import f1_score

def evaluate_model(model, dataset):
    y_true = []
    y_pred = []

    loss, acc = model.evaluate(dataset, verbose=0)

    for images, labels in dataset:
        probs = model.predict(images, verbose=0)
        y_true.extend(np.argmax(labels.numpy(), axis=1))
        y_pred.extend(np.argmax(probs, axis=1))

    macro_f1 = f1_score(y_true, y_pred, average="macro")
    weighted_f1 = f1_score(y_true, y_pred, average="weighted")

    return {
        "loss": loss,
        "accuracy": acc,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "y_true": y_true,
        "y_pred": y_pred
    }

In [31]:
all_transfer_results = []

for model_name in ["Lightweight CNN", "MobileNetV2", "EfficientNetB0"]:
    for seed in SEEDS:
        result = run_cross_dataset_experiment(model_name, seed)
        all_transfer_results.append(result)

per_seed_df = pd.DataFrame(all_transfer_results)

per_seed_csv = os.path.join(OUTPUT_DIR, "cross_dataset_transfer_per_seed_results.csv")
per_seed_df.to_csv(per_seed_csv, index=False)

print("Saved per-seed results to:", per_seed_csv)
per_seed_df

================================================================================
Model: Lightweight CNN | Seed: 42
================================================================================
Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 12s 101ms/step - accuracy: 0.4648 - loss: 1.0968 - val_accuracy: 0.4651 - val_loss: 1.0930
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.4648 - loss: 1.0929 - val_accuracy: 0.4651 - val_loss: 1.0891
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.4724 - loss: 1.0871 - val_accuracy: 0.4651 - val_loss: 1.0788
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.4863 - loss: 1.0768 - val_accuracy: 0.5256 - val_loss: 1.0708
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.5107 - loss: 1.0577 - val_accuracy: 0.5302 - val_loss: 1.0389
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.5148 - loss: 1.0146 - val_accuracy: 0.5209 - val_loss: 1.0029
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.5026 - loss: 0.9407 - val_accuracy: 0.5302 - val_loss: 0.9179
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.5334 - loss: 0.8432 - val_accuracy: 0.5581 - val_loss: 0.8598
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.5630 - loss: 0.7563 - val_accuracy: 0.6465 - val_loss: 0.7429
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.5997 - loss: 0.6964 - val_accuracy: 0.5860 - val_loss: 0.7754
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.6136 - loss: 0.6564 - val_accuracy: 0.6233 - val_loss: 0.6961
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.6200 - loss: 0.6370 - val_accuracy: 0.6047 - val_loss: 0.7424
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.6217 - loss: 0.6233 - val_accuracy: 0.6233 - val_loss: 0.7213
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.6194 - loss: 0.6130 - val_accuracy: 0.6651 - val_loss: 0.6590
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.6490 - loss: 0.6026 - val_accuracy: 0.6233 - val_loss: 0.6979
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.6496 - loss: 0.5764 - val_accuracy: 0.6651 - val_loss: 0.6501
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.6682 - loss: 0.5777 - val_accuracy: 0.6884 - val_loss: 0.6308
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.6653 - loss: 0.5631 - val_accuracy: 0.6605 - val_loss: 0.6639
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.6856 - loss: 0.5532 - val_accuracy: 0.6791 - val_loss: 0.6381
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.6920 - loss: 0.5376 - val_accuracy: 0.6977 - val_loss: 0.6311
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.7153 - loss: 0.5167 - val_accuracy: 0.7209 - val_loss: 0.5912
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.7269 - loss: 0.4973 - val_accuracy: 0.7442 - val_loss: 0.5476
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.7449 - loss: 0.4909 - val_accuracy: 0.7628 - val_loss: 0.5172
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.7565 - loss: 0.4789 - val_accuracy: 0.7628 - val_loss: 0.5719
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.7653 - loss: 0.4544 - val_accuracy: 0.7674 - val_loss: 0.5420
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.7862 - loss: 0.4345 - val_accuracy: 0.7721 - val_loss: 0.4851
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.7995 - loss: 0.4237 - val_accuracy: 0.7721 - val_loss: 0.4980
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8106 - loss: 0.4058 - val_accuracy: 0.8140 - val_loss: 0.4544
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.8205 - loss: 0.3899 - val_accuracy: 0.8186 - val_loss: 0.4187
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8361 - loss: 0.3776 - val_accuracy: 0.8465 - val_loss: 0.4074
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8425 - loss: 0.3697 - val_accuracy: 0.8140 - val_loss: 0.3950
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.8576 - loss: 0.3565 - val_accuracy: 0.8651 - val_loss: 0.3598
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8658 - loss: 0.3462 - val_accuracy: 0.8465 - val_loss: 0.3972
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8681 - loss: 0.3331 - val_accuracy: 0.8512 - val_loss: 0.3724
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8745 - loss: 0.3197 - val_accuracy: 0.8512 - val_loss: 0.3493
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8727 - loss: 0.3144 - val_accuracy: 0.8558 - val_loss: 0.3541
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8832 - loss: 0.3124 - val_accuracy: 0.8837 - val_loss: 0.3261
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8786 - loss: 0.2986 - val_accuracy: 0.8651 - val_loss: 0.3469
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8844 - loss: 0.2887 - val_accuracy: 0.8279 - val_loss: 0.3647
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8855 - loss: 0.2883 - val_accuracy: 0.8884 - val_loss: 0.2923
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8855 - loss: 0.2800 - val_accuracy: 0.8698 - val_loss: 0.2791
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8931 - loss: 0.2830 - val_accuracy: 0.8558 - val_loss: 0.3421
Epoch 43/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8667 - loss: 0.3667 - val_accuracy: 0.9133 - val_loss: 0.3512
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8633 - loss: 0.3626 - val_accuracy: 0.8933 - val_loss: 0.3528
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8667 - loss: 0.3592 - val_accuracy: 0.8800 - val_loss: 0.3448
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8692 - loss: 0.3567 - val_accuracy: 0.9200 - val_loss: 0.3485
Epoch 29/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8625 - loss: 0.3594 - val_accuracy: 0.9067 - val_loss: 0.3344
Epoch 30/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8683 - loss: 0.3522 - val_accuracy: 0.9133 - val_loss: 0.3338
Epoch 31/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8733 - loss: 0.3494 - val_accuracy: 0.9133 - val_loss: 0.3283
Epoch 32/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8742 - loss: 0.3417 - val_accuracy: 0.9200 - val_loss: 0.3332
Epoch 33/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8725 - loss: 0.3453 - val_accuracy: 0.9067 - val_loss: 0.3338
Epoch 34/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8683 - loss: 0.3398 - val_accuracy: 0.9067 - val_loss: 0.3218
Epoch 35/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8725 - loss: 0.3388 - val_accuracy: 0.9000 - val_loss: 0.3240
Epoch 36/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8800 - loss: 0.3340 - val_accuracy: 0.9000 - val_loss: 0.3131
Epoch 37/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8767 - loss: 0.3326 - val_accuracy: 0.9067 - val_loss: 0.3149
Epoch 38/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8833 - loss: 0.3298 - val_accuracy: 0.9133 - val_loss: 0.3161
Epoch 39/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.8750 - loss: 0.3406 - val_accuracy: 0.9067 - val_loss: 0.3090
Epoch 40/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8675 - loss: 0.3374 - val_accuracy: 0.9067 - val_loss: 0.3052
Epoch 41/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8833 - loss: 0.3255 - val_accuracy: 0.9067 - val_loss: 0.3037
Epoch 42/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8750 - loss: 0.3224 - val_accuracy: 0.9067 - val_loss: 0.3019
Epoch 43/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8858 - loss: 0.3177 - val_accuracy: 0.9267 - val_loss: 0.3069
Epoch 44/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8858 - loss: 0.3172 - val_accuracy: 0.9133 - val_loss: 0.3032
Epoch 45/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8817 - loss: 0.3128 - val_accuracy: 0.9133 - val_loss: 0.2968
Epoch 46/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8867 - loss: 0.3158 - val_accuracy: 0.9067 - val_loss: 0.2962
Epoch 47/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8817 - loss: 0.3141 - val_accuracy: 0.9200 - val_loss: 0.2962
Epoch 48/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8850 - loss: 0.3128 - val_accuracy: 0.9067 - val_loss: 0.2928
Epoch 49/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.8917 - loss: 0.3074 - val_accuracy: 0.9133 - val_loss: 0.2930
Epoch 50/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8800 - loss: 0.3180 - val_accuracy: 0.9133 - val_loss: 0.2927

Result:
{'model': 'Lightweight CNN', 'seed': 42, 'source_loss': 0.3185148537158966, 'source_accuracy': 0.8657407164573669, 'source_macro_f1': 0.8477703455964326, 'source_weighted_f1': 0.8663477022172675, 'zero_shot_loss': 0.833895742893219, 'zero_shot_accuracy': 0.7066666483879089, 'zero_shot_macro_f1': 0.7113964002575953, 'zero_shot_weighted_f1': 0.7113964002575954, 'finetuned_loss': 0.3031749427318573, 'finetuned_accuracy': 0.8666666746139526, 'finetuned_macro_f1': 0.8653907496012758, 'finetuned_weighted_f1': 0.8653907496012759, 'zero_shot_drop': 0.159074068069458, 'finetuned_drop': -0.0009259581565856934, 'zero_shot_ratio': 0.8162566862739307, 'finetuned_ratio': 1.0010695559755751, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_target_finetune_history.pkl'}

================================================================================
Model: Lightweight CNN | Seed: 123
================================================================================
Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 11s 100ms/step - accuracy: 0.0709 - loss: 1.0981 - val_accuracy: 0.0698 - val_loss: 1.1083
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.2278 - loss: 1.0941 - val_accuracy: 0.4744 - val_loss: 1.1009
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.4416 - loss: 1.0913 - val_accuracy: 0.4651 - val_loss: 1.0931
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.4509 - loss: 1.0873 - val_accuracy: 0.4791 - val_loss: 1.0942
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.4730 - loss: 1.0827 - val_accuracy: 0.4698 - val_loss: 1.0804
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.4683 - loss: 1.0760 - val_accuracy: 0.5070 - val_loss: 1.0861
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.4968 - loss: 1.0662 - val_accuracy: 0.4884 - val_loss: 1.0580
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.5009 - loss: 1.0494 - val_accuracy: 0.4837 - val_loss: 1.0219
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.5107 - loss: 1.0210 - val_accuracy: 0.4977 - val_loss: 1.0452
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.5247 - loss: 0.9777 - val_accuracy: 0.5070 - val_loss: 1.0063
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.5293 - loss: 0.9148 - val_accuracy: 0.6186 - val_loss: 0.9432
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.6002 - loss: 0.8338 - val_accuracy: 0.5395 - val_loss: 0.9085
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.5944 - loss: 0.7573 - val_accuracy: 0.6233 - val_loss: 0.8702
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.6055 - loss: 0.6980 - val_accuracy: 0.7209 - val_loss: 0.7327
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.6810 - loss: 0.6489 - val_accuracy: 0.7209 - val_loss: 0.7146
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.6996 - loss: 0.6123 - val_accuracy: 0.7442 - val_loss: 0.6331
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.7269 - loss: 0.5763 - val_accuracy: 0.7209 - val_loss: 0.6644
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.7385 - loss: 0.5571 - val_accuracy: 0.8279 - val_loss: 0.5914
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.7670 - loss: 0.5298 - val_accuracy: 0.7953 - val_loss: 0.5706
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.7827 - loss: 0.5168 - val_accuracy: 0.7907 - val_loss: 0.5531
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8036 - loss: 0.4858 - val_accuracy: 0.7953 - val_loss: 0.5310
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8257 - loss: 0.4562 - val_accuracy: 0.8372 - val_loss: 0.4892
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8431 - loss: 0.4351 - val_accuracy: 0.8000 - val_loss: 0.5670
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8449 - loss: 0.4218 - val_accuracy: 0.8279 - val_loss: 0.4546
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8483 - loss: 0.3938 - val_accuracy: 0.8000 - val_loss: 0.4761
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8518 - loss: 0.3822 - val_accuracy: 0.8930 - val_loss: 0.4012
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8530 - loss: 0.3792 - val_accuracy: 0.8233 - val_loss: 0.4245
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8635 - loss: 0.3526 - val_accuracy: 0.9023 - val_loss: 0.3778
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8768 - loss: 0.3354 - val_accuracy: 0.9070 - val_loss: 0.3657
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8681 - loss: 0.3336 - val_accuracy: 0.8558 - val_loss: 0.3663
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.8669 - loss: 0.3223 - val_accuracy: 0.9209 - val_loss: 0.3376
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8826 - loss: 0.3094 - val_accuracy: 0.8512 - val_loss: 0.4057
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8815 - loss: 0.3015 - val_accuracy: 0.8791 - val_loss: 0.3198
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8815 - loss: 0.3030 - val_accuracy: 0.9023 - val_loss: 0.3260
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8844 - loss: 0.2875 - val_accuracy: 0.9116 - val_loss: 0.3273
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8960 - loss: 0.2795 - val_accuracy: 0.9256 - val_loss: 0.3091
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9001 - loss: 0.2711 - val_accuracy: 0.9116 - val_loss: 0.3123
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.8913 - loss: 0.2605 - val_accuracy: 0.9256 - val_loss: 0.3004
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8983 - loss: 0.2567 - val_accuracy: 0.8977 - val_loss: 0.3227
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9006 - loss: 0.2594 - val_accuracy: 0.9256 - val_loss: 0.2788
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9059 - loss: 0.2506 - val_accuracy: 0.9209 - val_loss: 0.2811
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9024 - loss: 0.2499 - val_accuracy: 0.9209 - val_loss: 0.2882
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9070 - loss: 0.2318 - val_accuracy: 0.9070 - val_loss: 0.2608
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9070 - loss: 0.2366 - val_accuracy: 0.9256 - val_loss: 0.2656
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9134 - loss: 0.2294 - val_accuracy: 0.9302 - val_loss: 0.2572
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9152 - loss: 0.2231 - val_accuracy: 0.9302 - val_loss: 0.2562
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9169 - loss: 0.2194 - val_accuracy: 0.9209 - val_loss: 0.2705
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9157 - loss: 0.2161 - val_accuracy: 0.9256 - val_loss: 0.2509
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9123 - loss: 0.2223 - val_accuracy: 0.9256 - val_loss: 0.2370
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9181 - loss: 0.2199 - val_accuracy: 0.9395 - val_loss: 0.2354
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 5s 98ms/step - accuracy: 0.7650 - loss: 0.6435 - val_accuracy: 0.8400 - val_loss: 0.4085
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8108 - loss: 0.5434 - val_accuracy: 0.8533 - val_loss: 0.4050
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8075 - loss: 0.5061 - val_accuracy: 0.8533 - val_loss: 0.3834
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8125 - loss: 0.4798 - val_accuracy: 0.8933 - val_loss: 0.3755
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8350 - loss: 0.4574 - val_accuracy: 0.8933 - val_loss: 0.3709
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8392 - loss: 0.4435 - val_accuracy: 0.8933 - val_loss: 0.3705
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8425 - loss: 0.4322 - val_accuracy: 0.8933 - val_loss: 0.3673
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8425 - loss: 0.4343 - val_accuracy: 0.8867 - val_loss: 0.3615
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8525 - loss: 0.4179 - val_accuracy: 0.8467 - val_loss: 0.3793
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8442 - loss: 0.4181 - val_accuracy: 0.8933 - val_loss: 0.3581
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8475 - loss: 0.4102 - val_accuracy: 0.8600 - val_loss: 0.3614
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8525 - loss: 0.4139 - val_accuracy: 0.9000 - val_loss: 0.3522
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8525 - loss: 0.3988 - val_accuracy: 0.8867 - val_loss: 0.3433
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8533 - loss: 0.3999 - val_accuracy: 0.8800 - val_loss: 0.3497
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8542 - loss: 0.4026 - val_accuracy: 0.8933 - val_loss: 0.3401
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8550 - loss: 0.3991 - val_accuracy: 0.8800 - val_loss: 0.3361
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8575 - loss: 0.3902 - val_accuracy: 0.8933 - val_loss: 0.3371
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8583 - loss: 0.3917 - val_accuracy: 0.8800 - val_loss: 0.3398
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8550 - loss: 0.3866 - val_accuracy: 0.8933 - val_loss: 0.3328
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8492 - loss: 0.3895 - val_accuracy: 0.9067 - val_loss: 0.3308
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.8633 - loss: 0.3790 - val_accuracy: 0.8933 - val_loss: 0.3259
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8700 - loss: 0.3724 - val_accuracy: 0.8933 - val_loss: 0.3256
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8517 - loss: 0.3831 - val_accuracy: 0.9067 - val_loss: 0.3244
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8708 - loss: 0.3715 - val_accuracy: 0.8733 - val_loss: 0.3297
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8675 - loss: 0.3680 - val_accuracy: 0.9000 - val_loss: 0.3218
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.8700 - loss: 0.3673 - val_accuracy: 0.8867 - val_loss: 0.3207
Epoch 27/50

/tmp/ipykernel_58/4031514531.py:33: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  backbone = MobileNetV2(

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/50

2026-05-30 22:01:46.815188: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:01:47.012639: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

53/54 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4108 - loss: 1.0937

2026-05-30 22:01:58.291760: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:01:58.490834: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

54/54 ━━━━━━━━━━━━━━━━━━━━ 43s 424ms/step - accuracy: 0.5067 - loss: 0.9236 - val_accuracy: 0.4093 - val_loss: 1.1131
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.7955 - loss: 0.4772 - val_accuracy: 0.5721 - val_loss: 0.8950
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8867 - loss: 0.3081 - val_accuracy: 0.6744 - val_loss: 0.7044
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9268 - loss: 0.2324 - val_accuracy: 0.7628 - val_loss: 0.5797
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9489 - loss: 0.1793 - val_accuracy: 0.8093 - val_loss: 0.4714
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9535 - loss: 0.1592 - val_accuracy: 0.8512 - val_loss: 0.3703
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9628 - loss: 0.1291 - val_accuracy: 0.8977 - val_loss: 0.3139
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9721 - loss: 0.0978 - val_accuracy: 0.9256 - val_loss: 0.2565
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9727 - loss: 0.0966 - val_accuracy: 0.9349 - val_loss: 0.2017
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9820 - loss: 0.0860 - val_accuracy: 0.9581 - val_loss: 0.1669
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9797 - loss: 0.0768 - val_accuracy: 0.9674 - val_loss: 0.1389
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9837 - loss: 0.0651 - val_accuracy: 0.9767 - val_loss: 0.1154
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9866 - loss: 0.0549 - val_accuracy: 0.9767 - val_loss: 0.0977
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9831 - loss: 0.0571 - val_accuracy: 0.9767 - val_loss: 0.0822
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9861 - loss: 0.0498 - val_accuracy: 0.9767 - val_loss: 0.0701
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9890 - loss: 0.0413 - val_accuracy: 0.9767 - val_loss: 0.0577
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9936 - loss: 0.0372 - val_accuracy: 0.9814 - val_loss: 0.0494
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0375 - val_accuracy: 0.9907 - val_loss: 0.0459
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9913 - loss: 0.0367 - val_accuracy: 0.9953 - val_loss: 0.0400
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9954 - loss: 0.0275 - val_accuracy: 1.0000 - val_loss: 0.0343
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9942 - loss: 0.0300 - val_accuracy: 1.0000 - val_loss: 0.0306
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0240 - val_accuracy: 1.0000 - val_loss: 0.0273
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0199 - val_accuracy: 1.0000 - val_loss: 0.0250
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9948 - loss: 0.0295 - val_accuracy: 1.0000 - val_loss: 0.0246
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0204 - val_accuracy: 1.0000 - val_loss: 0.0229
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0140 - val_accuracy: 1.0000 - val_loss: 0.0205
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9971 - loss: 0.0198 - val_accuracy: 1.0000 - val_loss: 0.0194
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0195 - val_accuracy: 1.0000 - val_loss: 0.0186
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9954 - loss: 0.0177 - val_accuracy: 1.0000 - val_loss: 0.0165
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9971 - loss: 0.0146 - val_accuracy: 1.0000 - val_loss: 0.0161
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0129 - val_accuracy: 1.0000 - val_loss: 0.0152
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9988 - loss: 0.0126 - val_accuracy: 1.0000 - val_loss: 0.0147
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0137 - val_accuracy: 1.0000 - val_loss: 0.0138
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9977 - loss: 0.0133 - val_accuracy: 1.0000 - val_loss: 0.0131
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0156 - val_accuracy: 1.0000 - val_loss: 0.0130
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0113 - val_accuracy: 1.0000 - val_loss: 0.0123
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9988 - loss: 0.0103 - val_accuracy: 1.0000 - val_loss: 0.0117
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0123 - val_accuracy: 1.0000 - val_loss: 0.0114
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9936 - loss: 0.0177 - val_accuracy: 1.0000 - val_loss: 0.0110
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0090 - val_accuracy: 1.0000 - val_loss: 0.0105
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0077 - val_accuracy: 1.0000 - val_loss: 0.0100
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0096 - val_accuracy: 1.0000 - val_loss: 0.0097
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 1.0000 - val_loss: 0.0093
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0078 - val_accuracy: 1.0000 - val_loss: 0.0090
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0072 - val_accuracy: 1.0000 - val_loss: 0.0089
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 1.0000 - val_loss: 0.0085
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0067 - val_accuracy: 1.0000 - val_loss: 0.0082
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9988 - loss: 0.0102 - val_accuracy: 1.0000 - val_loss: 0.0084
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9983 - loss: 0.0082 - val_accuracy: 1.0000 - val_loss: 0.0081
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0076 - val_accuracy: 1.0000 - val_loss: 0.0078
Epoch 1/50
37/38 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8549 - loss: 0.4167

2026-05-30 22:05:51.463966: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:05:51.660168: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

38/38 ━━━━━━━━━━━━━━━━━━━━ 13s 311ms/step - accuracy: 0.9067 - loss: 0.2532 - val_accuracy: 0.9400 - val_loss: 0.1167
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9683 - loss: 0.0910 - val_accuracy: 0.9467 - val_loss: 0.1061
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9808 - loss: 0.0598 - val_accuracy: 0.9467 - val_loss: 0.1124
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9908 - loss: 0.0395 - val_accuracy: 0.9467 - val_loss: 0.1255
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9917 - loss: 0.0374 - val_accuracy: 0.9467 - val_loss: 0.1251
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9867 - loss: 0.0408 - val_accuracy: 0.9533 - val_loss: 0.1238
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9975 - loss: 0.0238 - val_accuracy: 0.9600 - val_loss: 0.1170

Result:
{'model': 'MobileNetV2', 'seed': 42, 'source_loss': 0.04979751631617546, 'source_accuracy': 0.9768518805503845, 'source_macro_f1': 0.9528276842002832, 'source_weighted_f1': 0.9776927712658255, 'zero_shot_loss': 0.455985426902771, 'zero_shot_accuracy': 0.8266666531562805, 'zero_shot_macro_f1': 0.8228021978021979, 'zero_shot_weighted_f1': 0.8228021978021978, 'finetuned_loss': 0.2254284918308258, 'finetuned_accuracy': 0.9133333563804626, 'finetuned_macro_f1': 0.9111068410211808, 'finetuned_weighted_f1': 0.9111068410211806, 'zero_shot_drop': 0.150185227394104, 'finetuned_drop': 0.06351852416992188, 'zero_shot_ratio': 0.8462558854782717, 'finetuned_ratio': 0.9349762994425175, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_target_finetune_history.pkl'}

================================================================================
Model: MobileNetV2 | Seed: 123
================================================================================

/tmp/ipykernel_58/4031514531.py:33: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  backbone = MobileNetV2(

Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 32s 310ms/step - accuracy: 0.4474 - loss: 0.9056 - val_accuracy: 0.1628 - val_loss: 1.6406
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8100 - loss: 0.4562 - val_accuracy: 0.2512 - val_loss: 1.2995
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8977 - loss: 0.2947 - val_accuracy: 0.3860 - val_loss: 1.0696
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9309 - loss: 0.2219 - val_accuracy: 0.5256 - val_loss: 0.8674
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9442 - loss: 0.1780 - val_accuracy: 0.6326 - val_loss: 0.7289
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9617 - loss: 0.1414 - val_accuracy: 0.6977 - val_loss: 0.6219
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9593 - loss: 0.1269 - val_accuracy: 0.7721 - val_loss: 0.5128
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9715 - loss: 0.1006 - val_accuracy: 0.8093 - val_loss: 0.4393
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9802 - loss: 0.0845 - val_accuracy: 0.8465 - val_loss: 0.3686
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9768 - loss: 0.0795 - val_accuracy: 0.8744 - val_loss: 0.3042
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9814 - loss: 0.0702 - val_accuracy: 0.9023 - val_loss: 0.2531
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9808 - loss: 0.0678 - val_accuracy: 0.9163 - val_loss: 0.2229
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9855 - loss: 0.0567 - val_accuracy: 0.9209 - val_loss: 0.1949
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9884 - loss: 0.0522 - val_accuracy: 0.9395 - val_loss: 0.1674
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9890 - loss: 0.0477 - val_accuracy: 0.9488 - val_loss: 0.1497
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0436 - val_accuracy: 0.9581 - val_loss: 0.1345
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9913 - loss: 0.0406 - val_accuracy: 0.9581 - val_loss: 0.1184
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9919 - loss: 0.0375 - val_accuracy: 0.9581 - val_loss: 0.1080
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9913 - loss: 0.0344 - val_accuracy: 0.9628 - val_loss: 0.0950
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9919 - loss: 0.0315 - val_accuracy: 0.9674 - val_loss: 0.0866
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9924 - loss: 0.0325 - val_accuracy: 0.9721 - val_loss: 0.0853
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0251 - val_accuracy: 0.9814 - val_loss: 0.0750
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9954 - loss: 0.0215 - val_accuracy: 0.9860 - val_loss: 0.0669
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9977 - loss: 0.0225 - val_accuracy: 0.9860 - val_loss: 0.0613
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0206 - val_accuracy: 0.9860 - val_loss: 0.0546
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9954 - loss: 0.0218 - val_accuracy: 0.9860 - val_loss: 0.0526
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9971 - loss: 0.0194 - val_accuracy: 0.9860 - val_loss: 0.0502
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9971 - loss: 0.0162 - val_accuracy: 0.9860 - val_loss: 0.0462
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9977 - loss: 0.0153 - val_accuracy: 0.9860 - val_loss: 0.0433
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0161 - val_accuracy: 0.9860 - val_loss: 0.0413
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0174 - val_accuracy: 0.9860 - val_loss: 0.0399
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9971 - loss: 0.0120 - val_accuracy: 0.9907 - val_loss: 0.0374
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9971 - loss: 0.0161 - val_accuracy: 0.9907 - val_loss: 0.0374
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9983 - loss: 0.0129 - val_accuracy: 0.9907 - val_loss: 0.0363
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9994 - loss: 0.0112 - val_accuracy: 0.9907 - val_loss: 0.0365
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9971 - loss: 0.0135 - val_accuracy: 0.9907 - val_loss: 0.0348
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0084 - val_accuracy: 0.9907 - val_loss: 0.0324
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9988 - loss: 0.0077 - val_accuracy: 0.9907 - val_loss: 0.0312
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9971 - loss: 0.0091 - val_accuracy: 0.9907 - val_loss: 0.0305
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0075 - val_accuracy: 0.9907 - val_loss: 0.0299
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0080 - val_accuracy: 0.9907 - val_loss: 0.0297
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9971 - loss: 0.0114 - val_accuracy: 0.9907 - val_loss: 0.0290
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9971 - loss: 0.0150 - val_accuracy: 0.9907 - val_loss: 0.0312
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 1.0000 - loss: 0.0066 - val_accuracy: 0.9907 - val_loss: 0.0299
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9907 - val_loss: 0.0292
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9983 - loss: 0.0065 - val_accuracy: 0.9907 - val_loss: 0.0285
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9983 - loss: 0.0080 - val_accuracy: 0.9907 - val_loss: 0.0279
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9988 - loss: 0.0079 - val_accuracy: 0.9907 - val_loss: 0.0274
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 1.0000 - loss: 0.0053 - val_accuracy: 0.9907 - val_loss: 0.0269
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.9907 - val_loss: 0.0260
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 9s 219ms/step - accuracy: 0.9025 - loss: 0.2447 - val_accuracy: 0.9600 - val_loss: 0.1204
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9775 - loss: 0.0772 - val_accuracy: 0.9800 - val_loss: 0.0992
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9867 - loss: 0.0539 - val_accuracy: 0.9800 - val_loss: 0.0926
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9850 - loss: 0.0499 - val_accuracy: 0.9867 - val_loss: 0.0914
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9900 - loss: 0.0478 - val_accuracy: 0.9867 - val_loss: 0.0852
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9900 - loss: 0.0503 - val_accuracy: 0.9867 - val_loss: 0.0802
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9892 - loss: 0.0390 - val_accuracy: 0.9867 - val_loss: 0.0798
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9942 - loss: 0.0269 - val_accuracy: 0.9867 - val_loss: 0.0734
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9917 - loss: 0.0291 - val_accuracy: 0.9867 - val_loss: 0.0679
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9983 - loss: 0.0195 - val_accuracy: 0.9867 - val_loss: 0.0724
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9950 - loss: 0.0212 - val_accuracy: 0.9867 - val_loss: 0.0715
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9975 - loss: 0.0208 - val_accuracy: 0.9867 - val_loss: 0.0688
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9967 - loss: 0.0161 - val_accuracy: 0.9867 - val_loss: 0.0649
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9983 - loss: 0.0136 - val_accuracy: 0.9867 - val_loss: 0.0649
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.9983 - loss: 0.0128 - val_accuracy: 0.9867 - val_loss: 0.0642
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9983 - loss: 0.0152 - val_accuracy: 0.9867 - val_loss: 0.0638
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.9867 - val_loss: 0.0647
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9975 - loss: 0.0149 - val_accuracy: 0.9867 - val_loss: 0.0584
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 1.0000 - loss: 0.0100 - val_accuracy: 0.9867 - val_loss: 0.0575
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9975 - loss: 0.0164 - val_accuracy: 0.9867 - val_loss: 0.0553
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0095 - val_accuracy: 0.9867 - val_loss: 0.0560
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0127 - val_accuracy: 0.9867 - val_loss: 0.0569
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9967 - loss: 0.0158 - val_accuracy: 0.9867 - val_loss: 0.0569
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9992 - loss: 0.0100 - val_accuracy: 0.9867 - val_loss: 0.0562
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9975 - loss: 0.0114 - val_accuracy: 0.9867 - val_loss: 0.0521
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9983 - loss: 0.0108 - val_accuracy: 0.9867 - val_loss: 0.0558
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0122 - val_accuracy: 0.9867 - val_loss: 0.0533
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0100 - val_accuracy: 0.9867 - val_loss: 0.0535
Epoch 29/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0089 - val_accuracy: 0.9867 - val_loss: 0.0536
Epoch 30/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.9867 - val_loss: 0.0450
Epoch 31/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9992 - loss: 0.0077 - val_accuracy: 0.9867 - val_loss: 0.0435
Epoch 32/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.9867 - val_loss: 0.0450
Epoch 33/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9992 - loss: 0.0066 - val_accuracy: 0.9867 - val_loss: 0.0452
Epoch 34/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 1.0000 - loss: 0.0080 - val_accuracy: 0.9867 - val_loss: 0.0436
Epoch 35/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.9983 - loss: 0.0081 - val_accuracy: 0.9867 - val_loss: 0.0439
Epoch 36/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9992 - loss: 0.0058 - val_accuracy: 0.9867 - val_loss: 0.0431
Epoch 37/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9983 - loss: 0.0067 - val_accuracy: 0.9867 - val_loss: 0.0417
Epoch 38/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9867 - val_loss: 0.0408
Epoch 39/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0064 - val_accuracy: 0.9867 - val_loss: 0.0415
Epoch 40/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0053 - val_accuracy: 0.9867 - val_loss: 0.0409
Epoch 41/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0050 - val_accuracy: 0.9867 - val_loss: 0.0408
Epoch 42/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9992 - loss: 0.0068 - val_accuracy: 0.9867 - val_loss: 0.0405
Epoch 43/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0067 - val_accuracy: 0.9867 - val_loss: 0.0421
Epoch 44/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9867 - val_loss: 0.0394
Epoch 45/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9992 - loss: 0.0046 - val_accuracy: 0.9867 - val_loss: 0.0403
Epoch 46/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9867 - val_loss: 0.0381
Epoch 47/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9867 - val_loss: 0.0382
Epoch 48/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9867 - val_loss: 0.0351
Epoch 49/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0053 - val_accuracy: 0.9867 - val_loss: 0.0362
Epoch 50/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9867 - val_loss: 0.0369

Result:
{'model': 'MobileNetV2', 'seed': 123, 'source_loss': 0.038022615015506744, 'source_accuracy': 0.9861111044883728, 'source_macro_f1': 0.9663524292965917, 'source_weighted_f1': 0.9866005962452662, 'zero_shot_loss': 0.31429362297058105, 'zero_shot_accuracy': 0.8533333539962769, 'zero_shot_macro_f1': 0.8475681181563535, 'zero_shot_weighted_f1': 0.8475681181563534, 'finetuned_loss': 0.0692438930273056, 'finetuned_accuracy': 0.9800000190734863, 'finetuned_macro_f1': 0.97999799979998, 'finetuned_weighted_f1': 0.9799979997999799, 'zero_shot_drop': 0.13277775049209595, 'finetuned_drop': 0.006111085414886475, 'zero_shot_ratio': 0.8653521394417463, 'finetuned_ratio': 0.9938028429179315, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_target_finetune_history.pkl'}

================================================================================
Model: MobileNetV2 | Seed: 2024
================================================================================

/tmp/ipykernel_58/4031514531.py:33: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  backbone = MobileNetV2(

Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 31s 298ms/step - accuracy: 0.2661 - loss: 1.2094 - val_accuracy: 0.3860 - val_loss: 1.3886
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.6775 - loss: 0.5765 - val_accuracy: 0.3907 - val_loss: 1.5151
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.8919 - loss: 0.3283 - val_accuracy: 0.4419 - val_loss: 1.5002
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9419 - loss: 0.2225 - val_accuracy: 0.4605 - val_loss: 1.4237
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9489 - loss: 0.1854 - val_accuracy: 0.5116 - val_loss: 1.2963
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9640 - loss: 0.1435 - val_accuracy: 0.5721 - val_loss: 1.1308
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9628 - loss: 0.1301 - val_accuracy: 0.6140 - val_loss: 0.9922
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9657 - loss: 0.1089 - val_accuracy: 0.6651 - val_loss: 0.8693
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9715 - loss: 0.0981 - val_accuracy: 0.7163 - val_loss: 0.7267
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9808 - loss: 0.0803 - val_accuracy: 0.7628 - val_loss: 0.6316
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9791 - loss: 0.0716 - val_accuracy: 0.8047 - val_loss: 0.5164
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9831 - loss: 0.0602 - val_accuracy: 0.8326 - val_loss: 0.4316
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9808 - loss: 0.0589 - val_accuracy: 0.8651 - val_loss: 0.3601
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9890 - loss: 0.0514 - val_accuracy: 0.8791 - val_loss: 0.3147
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9924 - loss: 0.0424 - val_accuracy: 0.8930 - val_loss: 0.2620
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9913 - loss: 0.0409 - val_accuracy: 0.9163 - val_loss: 0.2228
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9907 - loss: 0.0483 - val_accuracy: 0.9302 - val_loss: 0.1978
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9913 - loss: 0.0346 - val_accuracy: 0.9442 - val_loss: 0.1619
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9907 - loss: 0.0367 - val_accuracy: 0.9488 - val_loss: 0.1379
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9936 - loss: 0.0311 - val_accuracy: 0.9488 - val_loss: 0.1230
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9954 - loss: 0.0261 - val_accuracy: 0.9721 - val_loss: 0.1077
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9930 - loss: 0.0311 - val_accuracy: 0.9721 - val_loss: 0.0967
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0267 - val_accuracy: 0.9721 - val_loss: 0.0927
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0255 - val_accuracy: 0.9721 - val_loss: 0.0810
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9948 - loss: 0.0216 - val_accuracy: 0.9721 - val_loss: 0.0752
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9965 - loss: 0.0186 - val_accuracy: 0.9860 - val_loss: 0.0659
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0172 - val_accuracy: 0.9907 - val_loss: 0.0599
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0159 - val_accuracy: 0.9907 - val_loss: 0.0543
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9942 - loss: 0.0165 - val_accuracy: 0.9907 - val_loss: 0.0498
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9948 - loss: 0.0223 - val_accuracy: 0.9907 - val_loss: 0.0509
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0142 - val_accuracy: 0.9907 - val_loss: 0.0477
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0126 - val_accuracy: 0.9953 - val_loss: 0.0430
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0131 - val_accuracy: 0.9953 - val_loss: 0.0407
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0138 - val_accuracy: 0.9953 - val_loss: 0.0380
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9971 - loss: 0.0207 - val_accuracy: 0.9953 - val_loss: 0.0427
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9983 - loss: 0.0102 - val_accuracy: 0.9953 - val_loss: 0.0365
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9977 - loss: 0.0136 - val_accuracy: 0.9953 - val_loss: 0.0349
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9959 - loss: 0.0170 - val_accuracy: 0.9953 - val_loss: 0.0351
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.9953 - val_loss: 0.0317
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0091 - val_accuracy: 0.9953 - val_loss: 0.0298
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9994 - loss: 0.0090 - val_accuracy: 0.9953 - val_loss: 0.0301
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9994 - loss: 0.0075 - val_accuracy: 0.9953 - val_loss: 0.0283
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0088 - val_accuracy: 0.9953 - val_loss: 0.0269
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9994 - loss: 0.0068 - val_accuracy: 0.9953 - val_loss: 0.0280
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.9953 - val_loss: 0.0270
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9953 - val_loss: 0.0271
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9988 - loss: 0.0067 - val_accuracy: 0.9953 - val_loss: 0.0262
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0061 - val_accuracy: 0.9953 - val_loss: 0.0252
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0060 - val_accuracy: 0.9953 - val_loss: 0.0217
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9994 - loss: 0.0053 - val_accuracy: 0.9953 - val_loss: 0.0218
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 9s 213ms/step - accuracy: 0.8925 - loss: 0.2741 - val_accuracy: 0.9600 - val_loss: 0.1074
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.9700 - loss: 0.0840 - val_accuracy: 0.9733 - val_loss: 0.0965
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9733 - loss: 0.0731 - val_accuracy: 0.9733 - val_loss: 0.1017
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9858 - loss: 0.0527 - val_accuracy: 0.9733 - val_loss: 0.0971
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9908 - loss: 0.0392 - val_accuracy: 0.9733 - val_loss: 0.0968
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9942 - loss: 0.0284 - val_accuracy: 0.9733 - val_loss: 0.0989
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9925 - loss: 0.0275 - val_accuracy: 0.9667 - val_loss: 0.0975

Result:
{'model': 'MobileNetV2', 'seed': 2024, 'source_loss': 0.01799357868731022, 'source_accuracy': 0.9907407164573669, 'source_macro_f1': 0.9758333333333334, 'source_weighted_f1': 0.9907407407407407, 'zero_shot_loss': 0.2832900285720825, 'zero_shot_accuracy': 0.8999999761581421, 'zero_shot_macro_f1': 0.8986490822744192, 'zero_shot_weighted_f1': 0.8986490822744192, 'finetuned_loss': 0.23098795115947723, 'finetuned_accuracy': 0.9266666769981384, 'finetuned_macro_f1': 0.9257684650943078, 'finetuned_weighted_f1': 0.9257684650943079, 'zero_shot_drop': 0.09074074029922485, 'finetuned_drop': 0.06407403945922852, 'zero_shot_ratio': 0.9084112131540426, 'finetuned_ratio': 0.9353271361569344, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_target_finetune_history.pkl'}

================================================================================
Model: MobileNetV2 | Seed: 3407
================================================================================

/tmp/ipykernel_58/4031514531.py:33: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  backbone = MobileNetV2(

Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - accuracy: 0.4561 - loss: 0.9425 - val_accuracy: 0.4837 - val_loss: 1.1076
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.7804 - loss: 0.4748 - val_accuracy: 0.5814 - val_loss: 0.9220
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9030 - loss: 0.2863 - val_accuracy: 0.6465 - val_loss: 0.7972
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9372 - loss: 0.2107 - val_accuracy: 0.6744 - val_loss: 0.6956
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9512 - loss: 0.1739 - val_accuracy: 0.7163 - val_loss: 0.6249
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9663 - loss: 0.1351 - val_accuracy: 0.7442 - val_loss: 0.5155
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9715 - loss: 0.1176 - val_accuracy: 0.7767 - val_loss: 0.4507
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9698 - loss: 0.1048 - val_accuracy: 0.8326 - val_loss: 0.3953
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9715 - loss: 0.0895 - val_accuracy: 0.8558 - val_loss: 0.3310
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9773 - loss: 0.0764 - val_accuracy: 0.8791 - val_loss: 0.2902
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9808 - loss: 0.0667 - val_accuracy: 0.9023 - val_loss: 0.2429
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9855 - loss: 0.0640 - val_accuracy: 0.9163 - val_loss: 0.2093
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9878 - loss: 0.0536 - val_accuracy: 0.9302 - val_loss: 0.1828
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9884 - loss: 0.0520 - val_accuracy: 0.9349 - val_loss: 0.1605
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9890 - loss: 0.0438 - val_accuracy: 0.9488 - val_loss: 0.1366
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9884 - loss: 0.0421 - val_accuracy: 0.9628 - val_loss: 0.1206
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9919 - loss: 0.0365 - val_accuracy: 0.9674 - val_loss: 0.1093
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9901 - loss: 0.0416 - val_accuracy: 0.9674 - val_loss: 0.1030
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9936 - loss: 0.0313 - val_accuracy: 0.9674 - val_loss: 0.0912
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9936 - loss: 0.0301 - val_accuracy: 0.9721 - val_loss: 0.0781
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0261 - val_accuracy: 0.9721 - val_loss: 0.0729
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9977 - loss: 0.0242 - val_accuracy: 0.9721 - val_loss: 0.0706
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0220 - val_accuracy: 0.9721 - val_loss: 0.0682
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9930 - loss: 0.0218 - val_accuracy: 0.9721 - val_loss: 0.0634
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9965 - loss: 0.0188 - val_accuracy: 0.9721 - val_loss: 0.0603
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9977 - loss: 0.0155 - val_accuracy: 0.9721 - val_loss: 0.0602
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0173 - val_accuracy: 0.9767 - val_loss: 0.0562
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9942 - loss: 0.0172 - val_accuracy: 0.9814 - val_loss: 0.0530
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9971 - loss: 0.0169 - val_accuracy: 0.9814 - val_loss: 0.0531
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9977 - loss: 0.0139 - val_accuracy: 0.9814 - val_loss: 0.0518
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0127 - val_accuracy: 0.9860 - val_loss: 0.0498
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9983 - loss: 0.0147 - val_accuracy: 0.9860 - val_loss: 0.0513
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9965 - loss: 0.0171 - val_accuracy: 0.9860 - val_loss: 0.0485
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0121 - val_accuracy: 0.9860 - val_loss: 0.0469
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0092 - val_accuracy: 0.9860 - val_loss: 0.0451
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0101 - val_accuracy: 0.9860 - val_loss: 0.0438
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0090 - val_accuracy: 0.9860 - val_loss: 0.0435
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9988 - loss: 0.0089 - val_accuracy: 0.9860 - val_loss: 0.0420
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9983 - loss: 0.0102 - val_accuracy: 0.9860 - val_loss: 0.0405
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9977 - loss: 0.0144 - val_accuracy: 0.9814 - val_loss: 0.0409
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 0.9860 - val_loss: 0.0392
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9977 - loss: 0.0094 - val_accuracy: 0.9860 - val_loss: 0.0393
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0077 - val_accuracy: 0.9860 - val_loss: 0.0384
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0077 - val_accuracy: 0.9860 - val_loss: 0.0372
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0053 - val_accuracy: 0.9860 - val_loss: 0.0371
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.9860 - val_loss: 0.0377
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step - accuracy: 0.9994 - loss: 0.0065 - val_accuracy: 0.9860 - val_loss: 0.0369
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9860 - val_loss: 0.0365
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9994 - loss: 0.0075 - val_accuracy: 0.9860 - val_loss: 0.0361
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.9860 - val_loss: 0.0345
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 9s 209ms/step - accuracy: 0.9042 - loss: 0.2739 - val_accuracy: 0.9667 - val_loss: 0.1201
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.9642 - loss: 0.1011 - val_accuracy: 0.9733 - val_loss: 0.1077
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9775 - loss: 0.0696 - val_accuracy: 0.9733 - val_loss: 0.1067
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9817 - loss: 0.0601 - val_accuracy: 0.9733 - val_loss: 0.1056
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9858 - loss: 0.0500 - val_accuracy: 0.9733 - val_loss: 0.1004
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step - accuracy: 0.9867 - loss: 0.0460 - val_accuracy: 0.9733 - val_loss: 0.0970
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9992 - loss: 0.0230 - val_accuracy: 0.9733 - val_loss: 0.1000
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9975 - loss: 0.0228 - val_accuracy: 0.9733 - val_loss: 0.1035
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9950 - loss: 0.0261 - val_accuracy: 0.9733 - val_loss: 0.0972
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.9975 - loss: 0.0206 - val_accuracy: 0.9733 - val_loss: 0.0967
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9967 - loss: 0.0233 - val_accuracy: 0.9733 - val_loss: 0.1007
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9975 - loss: 0.0183 - val_accuracy: 0.9733 - val_loss: 0.0995
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9975 - loss: 0.0213 - val_accuracy: 0.9733 - val_loss: 0.0991
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 1.0000 - loss: 0.0109 - val_accuracy: 0.9733 - val_loss: 0.0977
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9992 - loss: 0.0118 - val_accuracy: 0.9733 - val_loss: 0.0961
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9975 - loss: 0.0157 - val_accuracy: 0.9733 - val_loss: 0.1004
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0183 - val_accuracy: 0.9667 - val_loss: 0.1015
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9983 - loss: 0.0123 - val_accuracy: 0.9667 - val_loss: 0.1032
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0089 - val_accuracy: 0.9667 - val_loss: 0.1030
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9992 - loss: 0.0077 - val_accuracy: 0.9667 - val_loss: 0.0966

Result:
{'model': 'MobileNetV2', 'seed': 3407, 'source_loss': 0.06368766725063324, 'source_accuracy': 0.9768518805503845, 'source_macro_f1': 0.9379446851762693, 'source_weighted_f1': 0.9765360770817358, 'zero_shot_loss': 0.2725314199924469, 'zero_shot_accuracy': 0.8933333158493042, 'zero_shot_macro_f1': 0.8905795779358998, 'zero_shot_weighted_f1': 0.8905795779358997, 'finetuned_loss': 0.03123694658279419, 'finetuned_accuracy': 0.9933333396911621, 'finetuned_macro_f1': 0.9933326665999934, 'finetuned_weighted_f1': 0.9933326665999933, 'zero_shot_drop': 0.08351856470108032, 'finetuned_drop': -0.016481459140777588, 'zero_shot_ratio': 0.9145023249031126, 'finetuned_ratio': 1.0168720145489114, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_target_finetune_history.pkl'}

================================================================================
Model: MobileNetV2 | Seed: 777
================================================================================

/tmp/ipykernel_58/4031514531.py:33: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  backbone = MobileNetV2(

Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - accuracy: 0.4608 - loss: 0.8878 - val_accuracy: 0.4233 - val_loss: 1.0581
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.8036 - loss: 0.4427 - val_accuracy: 0.5163 - val_loss: 0.9206
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9128 - loss: 0.2837 - val_accuracy: 0.6326 - val_loss: 0.7691
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9402 - loss: 0.2092 - val_accuracy: 0.7023 - val_loss: 0.6486
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9454 - loss: 0.1725 - val_accuracy: 0.7581 - val_loss: 0.5452
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9686 - loss: 0.1316 - val_accuracy: 0.8047 - val_loss: 0.4612
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9733 - loss: 0.1105 - val_accuracy: 0.8419 - val_loss: 0.4027
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9762 - loss: 0.0948 - val_accuracy: 0.8605 - val_loss: 0.3371
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9797 - loss: 0.0835 - val_accuracy: 0.8930 - val_loss: 0.2780
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9820 - loss: 0.0784 - val_accuracy: 0.9163 - val_loss: 0.2427
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9890 - loss: 0.0653 - val_accuracy: 0.9209 - val_loss: 0.2229
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9866 - loss: 0.0559 - val_accuracy: 0.9395 - val_loss: 0.1932
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9866 - loss: 0.0591 - val_accuracy: 0.9442 - val_loss: 0.1812
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9861 - loss: 0.0502 - val_accuracy: 0.9674 - val_loss: 0.1517
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9901 - loss: 0.0449 - val_accuracy: 0.9674 - val_loss: 0.1333
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9930 - loss: 0.0401 - val_accuracy: 0.9767 - val_loss: 0.1156
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9924 - loss: 0.0346 - val_accuracy: 0.9721 - val_loss: 0.1029
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9942 - loss: 0.0324 - val_accuracy: 0.9721 - val_loss: 0.0994
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9924 - loss: 0.0308 - val_accuracy: 0.9767 - val_loss: 0.0894
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9930 - loss: 0.0297 - val_accuracy: 0.9767 - val_loss: 0.0851
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9924 - loss: 0.0279 - val_accuracy: 0.9767 - val_loss: 0.0797
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9965 - loss: 0.0243 - val_accuracy: 0.9767 - val_loss: 0.0756
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9965 - loss: 0.0228 - val_accuracy: 0.9767 - val_loss: 0.0715
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9959 - loss: 0.0206 - val_accuracy: 0.9767 - val_loss: 0.0666
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0190 - val_accuracy: 0.9814 - val_loss: 0.0638
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0189 - val_accuracy: 0.9814 - val_loss: 0.0613
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9988 - loss: 0.0176 - val_accuracy: 0.9814 - val_loss: 0.0616
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9977 - loss: 0.0169 - val_accuracy: 0.9814 - val_loss: 0.0588
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0126 - val_accuracy: 0.9814 - val_loss: 0.0564
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9965 - loss: 0.0151 - val_accuracy: 0.9814 - val_loss: 0.0563
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.0136 - val_accuracy: 0.9814 - val_loss: 0.0560
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9965 - loss: 0.0148 - val_accuracy: 0.9814 - val_loss: 0.0565
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9983 - loss: 0.0106 - val_accuracy: 0.9814 - val_loss: 0.0545
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9994 - loss: 0.0105 - val_accuracy: 0.9814 - val_loss: 0.0517
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9988 - loss: 0.0114 - val_accuracy: 0.9814 - val_loss: 0.0506
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9959 - loss: 0.0129 - val_accuracy: 0.9814 - val_loss: 0.0466
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9983 - loss: 0.0093 - val_accuracy: 0.9814 - val_loss: 0.0470
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9988 - loss: 0.0080 - val_accuracy: 0.9814 - val_loss: 0.0488
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9977 - loss: 0.0125 - val_accuracy: 0.9814 - val_loss: 0.0516
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9988 - loss: 0.0102 - val_accuracy: 0.9814 - val_loss: 0.0483
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - accuracy: 0.9971 - loss: 0.0104 - val_accuracy: 0.9814 - val_loss: 0.0476
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 9s 214ms/step - accuracy: 0.8967 - loss: 0.2602 - val_accuracy: 0.9667 - val_loss: 0.1008
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9650 - loss: 0.0962 - val_accuracy: 0.9667 - val_loss: 0.0945
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9775 - loss: 0.0690 - val_accuracy: 0.9600 - val_loss: 0.0919
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9808 - loss: 0.0611 - val_accuracy: 0.9600 - val_loss: 0.0906
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9917 - loss: 0.0467 - val_accuracy: 0.9667 - val_loss: 0.0915
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9925 - loss: 0.0367 - val_accuracy: 0.9667 - val_loss: 0.0891
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9858 - loss: 0.0455 - val_accuracy: 0.9600 - val_loss: 0.0889
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9967 - loss: 0.0239 - val_accuracy: 0.9600 - val_loss: 0.0907
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9942 - loss: 0.0285 - val_accuracy: 0.9600 - val_loss: 0.0930
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9958 - loss: 0.0245 - val_accuracy: 0.9600 - val_loss: 0.0877
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.9975 - loss: 0.0229 - val_accuracy: 0.9667 - val_loss: 0.0895
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - accuracy: 0.9942 - loss: 0.0211 - val_accuracy: 0.9667 - val_loss: 0.0847
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9950 - loss: 0.0253 - val_accuracy: 0.9667 - val_loss: 0.0829
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9967 - loss: 0.0172 - val_accuracy: 0.9733 - val_loss: 0.0821
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9958 - loss: 0.0232 - val_accuracy: 0.9733 - val_loss: 0.0809
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9975 - loss: 0.0148 - val_accuracy: 0.9733 - val_loss: 0.0762
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9967 - loss: 0.0150 - val_accuracy: 0.9733 - val_loss: 0.0750
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9975 - loss: 0.0139 - val_accuracy: 0.9733 - val_loss: 0.0713
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9983 - loss: 0.0124 - val_accuracy: 0.9733 - val_loss: 0.0711
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9992 - loss: 0.0097 - val_accuracy: 0.9733 - val_loss: 0.0718
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.9983 - loss: 0.0110 - val_accuracy: 0.9733 - val_loss: 0.0722
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9992 - loss: 0.0117 - val_accuracy: 0.9733 - val_loss: 0.0704
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9983 - loss: 0.0117 - val_accuracy: 0.9733 - val_loss: 0.0656
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9983 - loss: 0.0130 - val_accuracy: 0.9733 - val_loss: 0.0671
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9975 - loss: 0.0095 - val_accuracy: 0.9733 - val_loss: 0.0665
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.9992 - loss: 0.0085 - val_accuracy: 0.9733 - val_loss: 0.0697
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9992 - loss: 0.0106 - val_accuracy: 0.9733 - val_loss: 0.0712
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9983 - loss: 0.0113 - val_accuracy: 0.9733 - val_loss: 0.0681

Result:
{'model': 'MobileNetV2', 'seed': 777, 'source_loss': 0.028468135744333267, 'source_accuracy': 0.9953703880310059, 'source_macro_f1': 0.988223948022943, 'source_weighted_f1': 0.9954288840385993, 'zero_shot_loss': 0.48050567507743835, 'zero_shot_accuracy': 0.8133333325386047, 'zero_shot_macro_f1': 0.8101868309831338, 'zero_shot_weighted_f1': 0.8101868309831338, 'finetuned_loss': 0.1327609270811081, 'finetuned_accuracy': 0.9399999976158142, 'finetuned_macro_f1': 0.9392843727464651, 'finetuned_weighted_f1': 0.9392843727464651, 'zero_shot_drop': 0.18203705549240112, 'finetuned_drop': 0.05537039041519165, 'zero_shot_ratio': 0.8171162637734299, 'finetuned_ratio': 0.9443720738721968, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_target_finetune_history.pkl'}

================================================================================
Model: EfficientNetB0 | Seed: 42
================================================================================
Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/50

2026-05-30 22:25:58.620877: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:25:58.827937: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

53/54 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4270 - loss: 1.0863

2026-05-30 22:26:14.022562: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:26:14.232247: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

54/54 ━━━━━━━━━━━━━━━━━━━━ 56s 535ms/step - accuracy: 0.4956 - loss: 1.0269 - val_accuracy: 0.5116 - val_loss: 0.9654
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.6880 - loss: 0.8366 - val_accuracy: 0.7674 - val_loss: 0.7647
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step - accuracy: 0.7978 - loss: 0.6853 - val_accuracy: 0.8372 - val_loss: 0.6204
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.8565 - loss: 0.5762 - val_accuracy: 0.8930 - val_loss: 0.5121
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.8815 - loss: 0.4838 - val_accuracy: 0.9302 - val_loss: 0.4313
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9047 - loss: 0.4218 - val_accuracy: 0.9349 - val_loss: 0.3687
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9152 - loss: 0.3693 - val_accuracy: 0.9535 - val_loss: 0.3176
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9250 - loss: 0.3158 - val_accuracy: 0.9581 - val_loss: 0.2742
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9332 - loss: 0.2795 - val_accuracy: 0.9581 - val_loss: 0.2403
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9425 - loss: 0.2539 - val_accuracy: 0.9814 - val_loss: 0.2105
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9442 - loss: 0.2298 - val_accuracy: 0.9814 - val_loss: 0.1880
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9477 - loss: 0.2030 - val_accuracy: 0.9907 - val_loss: 0.1655
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9564 - loss: 0.1802 - val_accuracy: 0.9907 - val_loss: 0.1486
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9570 - loss: 0.1660 - val_accuracy: 0.9907 - val_loss: 0.1348
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9651 - loss: 0.1591 - val_accuracy: 0.9907 - val_loss: 0.1224
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - accuracy: 0.9680 - loss: 0.1365 - val_accuracy: 0.9907 - val_loss: 0.1106
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9634 - loss: 0.1293 - val_accuracy: 0.9907 - val_loss: 0.1004
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9657 - loss: 0.1250 - val_accuracy: 0.9907 - val_loss: 0.0926
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9686 - loss: 0.1194 - val_accuracy: 0.9907 - val_loss: 0.0840
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9744 - loss: 0.1035 - val_accuracy: 0.9907 - val_loss: 0.0774
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9744 - loss: 0.1009 - val_accuracy: 0.9907 - val_loss: 0.0712
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9802 - loss: 0.0934 - val_accuracy: 0.9907 - val_loss: 0.0662
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9826 - loss: 0.0827 - val_accuracy: 0.9907 - val_loss: 0.0605
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9797 - loss: 0.0815 - val_accuracy: 0.9907 - val_loss: 0.0562
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9814 - loss: 0.0768 - val_accuracy: 0.9907 - val_loss: 0.0523
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9814 - loss: 0.0676 - val_accuracy: 0.9907 - val_loss: 0.0490
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9831 - loss: 0.0722 - val_accuracy: 0.9907 - val_loss: 0.0465
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9802 - loss: 0.0726 - val_accuracy: 0.9953 - val_loss: 0.0441
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.9808 - loss: 0.0677 - val_accuracy: 0.9953 - val_loss: 0.0409
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9826 - loss: 0.0583 - val_accuracy: 0.9953 - val_loss: 0.0382
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9861 - loss: 0.0599 - val_accuracy: 0.9953 - val_loss: 0.0363
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step - accuracy: 0.9849 - loss: 0.0542 - val_accuracy: 0.9953 - val_loss: 0.0340
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9797 - loss: 0.0588 - val_accuracy: 1.0000 - val_loss: 0.0325
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9843 - loss: 0.0531 - val_accuracy: 1.0000 - val_loss: 0.0310
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.9861 - loss: 0.0468 - val_accuracy: 1.0000 - val_loss: 0.0296
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9855 - loss: 0.0496 - val_accuracy: 1.0000 - val_loss: 0.0281
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9878 - loss: 0.0476 - val_accuracy: 1.0000 - val_loss: 0.0267
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9884 - loss: 0.0493 - val_accuracy: 1.0000 - val_loss: 0.0255
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9849 - loss: 0.0496 - val_accuracy: 1.0000 - val_loss: 0.0242
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9872 - loss: 0.0432 - val_accuracy: 1.0000 - val_loss: 0.0230
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9930 - loss: 0.0389 - val_accuracy: 1.0000 - val_loss: 0.0222
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9919 - loss: 0.0373 - val_accuracy: 1.0000 - val_loss: 0.0211
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9884 - loss: 0.0381 - val_accuracy: 1.0000 - val_loss: 0.0201
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9907 - loss: 0.0351 - val_accuracy: 1.0000 - val_loss: 0.0191
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9866 - loss: 0.0389 - val_accuracy: 1.0000 - val_loss: 0.0180
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9954 - loss: 0.0309 - val_accuracy: 1.0000 - val_loss: 0.0173
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9913 - loss: 0.0295 - val_accuracy: 1.0000 - val_loss: 0.0165
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9936 - loss: 0.0303 - val_accuracy: 1.0000 - val_loss: 0.0159
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9907 - loss: 0.0300 - val_accuracy: 1.0000 - val_loss: 0.0154
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - accuracy: 0.9924 - loss: 0.0307 - val_accuracy: 1.0000 - val_loss: 0.0150
Epoch 1/50
37/38 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8486 - loss: 0.3495

2026-05-30 22:30:41.653805: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
2026-05-30 22:30:41.859494: E external/local_xla/xla/stream_executor/cuda/cuda_timer.cc:86] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

38/38 ━━━━━━━━━━━━━━━━━━━━ 17s 425ms/step - accuracy: 0.8817 - loss: 0.2799 - val_accuracy: 0.9667 - val_loss: 0.1372
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - accuracy: 0.9425 - loss: 0.1648 - val_accuracy: 0.9733 - val_loss: 0.1047
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9675 - loss: 0.1189 - val_accuracy: 0.9667 - val_loss: 0.0915
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9750 - loss: 0.0921 - val_accuracy: 0.9667 - val_loss: 0.0831
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9833 - loss: 0.0850 - val_accuracy: 0.9667 - val_loss: 0.0772
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9733 - loss: 0.0859 - val_accuracy: 0.9667 - val_loss: 0.0741
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9908 - loss: 0.0640 - val_accuracy: 0.9667 - val_loss: 0.0710
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9867 - loss: 0.0678 - val_accuracy: 0.9667 - val_loss: 0.0673
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9892 - loss: 0.0696 - val_accuracy: 0.9667 - val_loss: 0.0647
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9850 - loss: 0.0606 - val_accuracy: 0.9667 - val_loss: 0.0636
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9842 - loss: 0.0623 - val_accuracy: 0.9733 - val_loss: 0.0612
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 4s 76ms/step - accuracy: 0.9875 - loss: 0.0581 - val_accuracy: 0.9800 - val_loss: 0.0596
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9900 - loss: 0.0495 - val_accuracy: 0.9800 - val_loss: 0.0586
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9908 - loss: 0.0499 - val_accuracy: 0.9867 - val_loss: 0.0573
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9900 - loss: 0.0501 - val_accuracy: 0.9867 - val_loss: 0.0565
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9892 - loss: 0.0440 - val_accuracy: 0.9867 - val_loss: 0.0562
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9942 - loss: 0.0415 - val_accuracy: 0.9867 - val_loss: 0.0564
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9917 - loss: 0.0433 - val_accuracy: 0.9867 - val_loss: 0.0552
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9933 - loss: 0.0395 - val_accuracy: 0.9867 - val_loss: 0.0545
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9917 - loss: 0.0380 - val_accuracy: 0.9867 - val_loss: 0.0538
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9900 - loss: 0.0393 - val_accuracy: 0.9867 - val_loss: 0.0526
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9908 - loss: 0.0429 - val_accuracy: 0.9867 - val_loss: 0.0523
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9942 - loss: 0.0346 - val_accuracy: 0.9867 - val_loss: 0.0522
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9958 - loss: 0.0270 - val_accuracy: 0.9867 - val_loss: 0.0516
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9967 - loss: 0.0306 - val_accuracy: 0.9867 - val_loss: 0.0508
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9967 - loss: 0.0269 - val_accuracy: 0.9867 - val_loss: 0.0513
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9900 - loss: 0.0368 - val_accuracy: 0.9867 - val_loss: 0.0514
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9942 - loss: 0.0392 - val_accuracy: 0.9867 - val_loss: 0.0497
Epoch 29/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.9967 - loss: 0.0274 - val_accuracy: 0.9867 - val_loss: 0.0496
Epoch 30/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9983 - loss: 0.0260 - val_accuracy: 0.9867 - val_loss: 0.0493
Epoch 31/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9967 - loss: 0.0249 - val_accuracy: 0.9867 - val_loss: 0.0498
Epoch 32/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9942 - loss: 0.0284 - val_accuracy: 0.9867 - val_loss: 0.0499
Epoch 33/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9975 - loss: 0.0299 - val_accuracy: 0.9867 - val_loss: 0.0497
Epoch 34/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9933 - loss: 0.0315 - val_accuracy: 0.9867 - val_loss: 0.0497
Epoch 35/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.9958 - loss: 0.0273 - val_accuracy: 0.9867 - val_loss: 0.0487
Epoch 36/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9925 - loss: 0.0281 - val_accuracy: 0.9867 - val_loss: 0.0481
Epoch 37/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9992 - loss: 0.0202 - val_accuracy: 0.9867 - val_loss: 0.0484
Epoch 38/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9958 - loss: 0.0240 - val_accuracy: 0.9867 - val_loss: 0.0488
Epoch 39/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9925 - loss: 0.0306 - val_accuracy: 0.9867 - val_loss: 0.0493
Epoch 40/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9975 - loss: 0.0216 - val_accuracy: 0.9867 - val_loss: 0.0485
Epoch 41/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9967 - loss: 0.0231 - val_accuracy: 0.9867 - val_loss: 0.0493

Result:
{'model': 'EfficientNetB0', 'seed': 42, 'source_loss': 0.03310740739107132, 'source_accuracy': 1.0, 'source_macro_f1': 1.0, 'source_weighted_f1': 1.0, 'zero_shot_loss': 0.2168896496295929, 'zero_shot_accuracy': 0.9133333563804626, 'zero_shot_macro_f1': 0.9117690807855433, 'zero_shot_weighted_f1': 0.9117690807855433, 'finetuned_loss': 0.05003775656223297, 'finetuned_accuracy': 0.9666666388511658, 'finetuned_macro_f1': 0.9664424648850632, 'finetuned_weighted_f1': 0.9664424648850632, 'zero_shot_drop': 0.08666664361953735, 'finetuned_drop': 0.03333336114883423, 'zero_shot_ratio': 0.9133333563804626, 'finetuned_ratio': 0.9666666388511658, 'source_model_path': 'cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_source.keras', 'finetuned_model_path': 'cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_target_finetuned.keras', 'source_history_path': 'cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_source_history.pkl', 'target_history_path': 'cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_target_finetune_history.pkl'}

================================================================================
Model: EfficientNetB0 | Seed: 123
================================================================================
Epoch 1/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 52s 485ms/step - accuracy: 0.4404 - loss: 1.0349 - val_accuracy: 0.4140 - val_loss: 1.0545
Epoch 2/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.6415 - loss: 0.8446 - val_accuracy: 0.6884 - val_loss: 0.8472
Epoch 3/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.7635 - loss: 0.6908 - val_accuracy: 0.8372 - val_loss: 0.6760
Epoch 4/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.8483 - loss: 0.5746 - val_accuracy: 0.9023 - val_loss: 0.5501
Epoch 5/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.8797 - loss: 0.4843 - val_accuracy: 0.9163 - val_loss: 0.4556
Epoch 6/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.8983 - loss: 0.4116 - val_accuracy: 0.9256 - val_loss: 0.3820
Epoch 7/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9024 - loss: 0.3626 - val_accuracy: 0.9349 - val_loss: 0.3295
Epoch 8/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9285 - loss: 0.3114 - val_accuracy: 0.9442 - val_loss: 0.2880
Epoch 9/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9297 - loss: 0.2747 - val_accuracy: 0.9488 - val_loss: 0.2527
Epoch 10/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9367 - loss: 0.2494 - val_accuracy: 0.9535 - val_loss: 0.2253
Epoch 11/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9390 - loss: 0.2239 - val_accuracy: 0.9535 - val_loss: 0.2037
Epoch 12/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9407 - loss: 0.2057 - val_accuracy: 0.9581 - val_loss: 0.1827
Epoch 13/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9512 - loss: 0.1857 - val_accuracy: 0.9674 - val_loss: 0.1659
Epoch 14/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9582 - loss: 0.1688 - val_accuracy: 0.9721 - val_loss: 0.1523
Epoch 15/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9558 - loss: 0.1516 - val_accuracy: 0.9767 - val_loss: 0.1409
Epoch 16/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9593 - loss: 0.1444 - val_accuracy: 0.9767 - val_loss: 0.1312
Epoch 17/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.9663 - loss: 0.1289 - val_accuracy: 0.9767 - val_loss: 0.1205
Epoch 18/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9686 - loss: 0.1249 - val_accuracy: 0.9767 - val_loss: 0.1124
Epoch 19/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9709 - loss: 0.1168 - val_accuracy: 0.9814 - val_loss: 0.1059
Epoch 20/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9686 - loss: 0.1131 - val_accuracy: 0.9860 - val_loss: 0.0987
Epoch 21/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9739 - loss: 0.1045 - val_accuracy: 0.9860 - val_loss: 0.0938
Epoch 22/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9802 - loss: 0.0913 - val_accuracy: 0.9860 - val_loss: 0.0881
Epoch 23/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9756 - loss: 0.0880 - val_accuracy: 0.9860 - val_loss: 0.0838
Epoch 24/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 69ms/step - accuracy: 0.9831 - loss: 0.0842 - val_accuracy: 0.9860 - val_loss: 0.0802
Epoch 25/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9802 - loss: 0.0846 - val_accuracy: 0.9860 - val_loss: 0.0760
Epoch 26/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9756 - loss: 0.0840 - val_accuracy: 0.9860 - val_loss: 0.0731
Epoch 27/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9814 - loss: 0.0735 - val_accuracy: 0.9907 - val_loss: 0.0706
Epoch 28/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9808 - loss: 0.0725 - val_accuracy: 0.9907 - val_loss: 0.0677
Epoch 29/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9884 - loss: 0.0617 - val_accuracy: 0.9907 - val_loss: 0.0649
Epoch 30/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9820 - loss: 0.0627 - val_accuracy: 0.9907 - val_loss: 0.0622
Epoch 31/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9750 - loss: 0.0670 - val_accuracy: 0.9907 - val_loss: 0.0603
Epoch 32/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9884 - loss: 0.0510 - val_accuracy: 0.9907 - val_loss: 0.0582
Epoch 33/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9837 - loss: 0.0576 - val_accuracy: 0.9907 - val_loss: 0.0568
Epoch 34/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9837 - loss: 0.0593 - val_accuracy: 0.9907 - val_loss: 0.0546
Epoch 35/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9884 - loss: 0.0497 - val_accuracy: 0.9907 - val_loss: 0.0536
Epoch 36/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9861 - loss: 0.0537 - val_accuracy: 0.9907 - val_loss: 0.0523
Epoch 37/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9895 - loss: 0.0424 - val_accuracy: 0.9907 - val_loss: 0.0511
Epoch 38/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9901 - loss: 0.0424 - val_accuracy: 0.9907 - val_loss: 0.0493
Epoch 39/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9901 - loss: 0.0437 - val_accuracy: 0.9907 - val_loss: 0.0479
Epoch 40/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - accuracy: 0.9924 - loss: 0.0386 - val_accuracy: 0.9907 - val_loss: 0.0467
Epoch 41/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9907 - loss: 0.0403 - val_accuracy: 0.9907 - val_loss: 0.0459
Epoch 42/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9913 - loss: 0.0406 - val_accuracy: 0.9907 - val_loss: 0.0452
Epoch 43/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9890 - loss: 0.0430 - val_accuracy: 0.9907 - val_loss: 0.0445
Epoch 44/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.9901 - loss: 0.0349 - val_accuracy: 0.9907 - val_loss: 0.0436
Epoch 45/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.9930 - loss: 0.0340 - val_accuracy: 0.9907 - val_loss: 0.0425
Epoch 46/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9930 - loss: 0.0326 - val_accuracy: 0.9907 - val_loss: 0.0420
Epoch 47/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9907 - loss: 0.0319 - val_accuracy: 0.9907 - val_loss: 0.0413
Epoch 48/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step - accuracy: 0.9913 - loss: 0.0302 - val_accuracy: 0.9907 - val_loss: 0.0409
Epoch 49/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9942 - loss: 0.0285 - val_accuracy: 0.9907 - val_loss: 0.0401
Epoch 50/50
54/54 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - accuracy: 0.9901 - loss: 0.0284 - val_accuracy: 0.9907 - val_loss: 0.0388
Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 15s 376ms/step - accuracy: 0.9017 - loss: 0.2367 - val_accuracy: 0.9867 - val_loss: 0.0772
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9608 - loss: 0.1343 - val_accuracy: 0.9933 - val_loss: 0.0559
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9775 - loss: 0.1025 - val_accuracy: 0.9933 - val_loss: 0.0472
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.9775 - loss: 0.0954 - val_accuracy: 0.9933 - val_loss: 0.0425
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9733 - loss: 0.0965 - val_accuracy: 0.9933 - val_loss: 0.0399
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9808 - loss: 0.0862 - val_accuracy: 0.9933 - val_loss: 0.0384
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9842 - loss: 0.0776 - val_accuracy: 0.9933 - val_loss: 0.0369
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9858 - loss: 0.0653 - val_accuracy: 0.9933 - val_loss: 0.0345
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9842 - loss: 0.0599 - val_accuracy: 0.9933 - val_loss: 0.0326
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9850 - loss: 0.0613 - val_accuracy: 0.9933 - val_loss: 0.0314
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9817 - loss: 0.0660 - val_accuracy: 0.9933 - val_loss: 0.0305
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9842 - loss: 0.0575 - val_accuracy: 0.9867 - val_loss: 0.0297
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9883 - loss: 0.0507 - val_accuracy: 0.9867 - val_loss: 0.0290
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9883 - loss: 0.0537 - val_accuracy: 0.9867 - val_loss: 0.0281
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9908 - loss: 0.0455 - val_accuracy: 0.9867 - val_loss: 0.0275
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9917 - loss: 0.0441 - val_accuracy: 0.9867 - val_loss: 0.0267
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9933 - loss: 0.0404 - val_accuracy: 0.9867 - val_loss: 0.0260
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9908 - loss: 0.0434 - val_accuracy: 0.9867 - val_loss: 0.0255
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9892 - loss: 0.0440 - val_accuracy: 0.9867 - val_loss: 0.0243
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9900 - loss: 0.0423 - val_accuracy: 0.9867 - val_loss: 0.0229
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.9900 - loss: 0.0408 - val_accuracy: 0.9933 - val_loss: 0.0225
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9950 - loss: 0.0400 - val_accuracy: 0.9867 - val_loss: 0.0229
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9917 - loss: 0.0399 - val_accuracy: 0.9867 - val_loss: 0.0233
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9875 - loss: 0.0416 - val_accuracy: 0.9867 - val_loss: 0.0230
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9917 - loss: 0.0319 - val_accuracy: 0.9933 - val_loss: 0.0219
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9950 - loss: 0.0318 - val_accuracy: 0.9867 - val_loss: 0.0221
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9942 - loss: 0.0339 - val_accuracy: 0.9867 - val_loss: 0.0219
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9925 - loss: 0.0343 - val_accuracy: 0.9867 - val_loss: 0.0219
Epoch 29/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9933 - loss: 0.0358 - val_accuracy: 0.9867 - val_loss: 0.0213
Epoch 30/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9958 - loss: 0.0299 - val_accuracy: 0.9867 - val_loss: 0.0212
Epoch 31/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9900 - loss: 0.0337 - val_accuracy: 0.9933 - val_loss: 0.0207
Epoch 32/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.9958 - loss: 0.0264 - val_accuracy: 0.9867 - val_loss: 0.0206
Epoch 33/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9917 - loss: 0.0334 - val_accuracy: 0.9867 - val_loss: 0.0213
Epoch 34/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9908 - loss: 0.0330 - val_accuracy: 0.9867 - val_loss: 0.0216
Epoch 35/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9950 - loss: 0.0285 - val_accuracy: 0.9867 - val_loss: 0.0217
Epoch 36/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9958 - loss: 0.0276 - val_accuracy: 0.9867 - val_loss: 0.0206
Epoch 37/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9983 - loss: 0.0260 - val_accuracy: 0.9867 - val_loss: 0.0201
Epoch 38/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9958 - loss: 0.0238 - val_accuracy: 0.9933 - val_loss: 0.0195
Epoch 39/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9942 - loss: 0.0248 - val_accuracy: 0.9933 - val_loss: 0.0191
Epoch 40/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9950 - loss: 0.0247 - val_accuracy: 0.9933 - val_loss: 0.0192
Epoch 41/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9950 - loss: 0.0243 - val_accuracy: 0.9933 - val_loss: 0.0186
Epoch 42/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.9967 - loss: 0.0247 - val_accuracy: 0.9933 - val_loss: 0.0184
Epoch 43/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.9883 - loss: 0.0336 - val_accuracy: 0.9933 - val_loss: 0.0178
Epoch 44/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9950 - loss: 0.0193 - val_accuracy: 0.9933 - val_loss: 0.0179
Epoch 45/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9950 - loss: 0.0239 - val_accuracy: 0.9933 - val_loss: 0.0179
Epoch 46/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9958 - loss: 0.0181 - val_accuracy: 0.9933 - val_loss: 0.0181
Epoch 47/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9942 - loss: 0.0225 - val_accuracy: 0.9933 - val_loss: 0.0179
Epoch 48/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9942 - loss: 0.0225 - val_accuracy: 0.9933 - val_loss: 0.0179

Result:

,model,seed,source_loss,source_accuracy,source_macro_f1,source_weighted_f1,zero_shot_loss,zero_shot_accuracy,zero_shot_macro_f1,zero_shot_weighted_f1,...,finetuned_macro_f1,finetuned_weighted_f1,zero_shot_drop,finetuned_drop,zero_shot_ratio,finetuned_ratio,source_model_path,finetuned_model_path,source_history_path,target_history_path
0,Lightweight CNN,42,0.318515,0.865741,0.847770,0.866348,0.833896,0.706667,0.711396,0.711396,...,0.865391,0.865391,0.159074,-0.000926,0.816257,1.001070,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
1,Lightweight CNN,123,0.205209,0.912037,0.874069,0.914839,1.200278,0.653333,0.650815,0.650815,...,0.906754,0.906754,0.258704,0.005370,0.716345,0.994112,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
2,Lightweight CNN,2024,0.266094,0.935185,0.909735,0.936036,0.979063,0.680000,0.677169,0.677169,...,0.839691,0.839691,0.255185,0.095185,0.727129,0.898218,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
3,Lightweight CNN,3407,0.306253,0.884259,0.826766,0.889026,0.968668,0.720000,0.715678,0.715678,...,0.873644,0.873644,0.164259,0.010926,0.814241,0.987644,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
4,Lightweight CNN,777,0.326228,0.893519,0.874404,0.895361,1.188257,0.533333,0.503200,0.503200,...,0.906242,0.906242,0.360185,-0.013148,0.596891,1.014715,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
5,MobileNetV2,42,0.049798,0.976852,0.952828,0.977693,0.455985,0.826667,0.822802,0.822802,...,0.911107,0.911107,0.150185,0.063519,0.846256,0.934976,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
6,MobileNetV2,123,0.038023,0.986111,0.966352,0.986601,0.314294,0.853333,0.847568,0.847568,...,0.979998,0.979998,0.132778,0.006111,0.865352,0.993803,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
7,MobileNetV2,2024,0.017994,0.990741,0.975833,0.990741,0.283290,0.900000,0.898649,0.898649,...,0.925768,0.925768,0.090741,0.064074,0.908411,0.935327,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
8,MobileNetV2,3407,0.063688,0.976852,0.937945,0.976536,0.272531,0.893333,0.890580,0.890580,...,0.993333,0.993333,0.083519,-0.016481,0.914502,1.016872,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
9,MobileNetV2,777,0.028468,0.995370,0.988224,0.995429,0.480506,0.813333,0.810187,0.810187,...,0.939284,0.939284,0.182037,0.055370,0.817116,0.944372,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
10,EfficientNetB0,42,0.033107,1.000000,1.000000,1.000000,0.216890,0.913333,0.911769,0.911769,...,0.966442,0.966442,0.086667,0.033333,0.913333,0.966667,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
11,EfficientNetB0,123,0.031025,0.990741,0.977025,0.990966,0.159753,0.933333,0.933269,0.933269,...,0.993333,0.993333,0.057407,-0.002593,0.942056,1.002617,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
12,EfficientNetB0,2024,0.056153,0.990741,0.977025,0.990966,0.213706,0.913333,0.912830,0.912830,...,1.000000,1.000000,0.077407,-0.009259,0.921869,1.009346,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
13,EfficientNetB0,3407,0.023716,1.000000,1.000000,1.000000,0.231646,0.900000,0.898468,0.898468,...,0.993333,0.993333,0.100000,0.006667,0.900000,0.993333,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...
14,EfficientNetB0,777,0.027880,0.995370,0.988224,0.995429,0.206714,0.926667,0.926810,0.926810,...,0.993333,0.993333,0.068704,0.002037,0.930977,0.997953,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/models/...,cross_dataset_transfer_20260530-210441/histori...,cross_dataset_transfer_20260530-210441/histori...

In [34]:
def mean_std_percent(series):
    mean = series.mean() * 100
    std = series.std(ddof=0) * 100
    return f"{mean:.2f} ± {std:.2f}"


def mean_std_ratio(series):
    mean = series.mean()
    std = series.std(ddof=0)
    return f"{mean:.4f} ± {std:.4f}"


summary_rows = []

for model_name, group in per_seed_df.groupby("model"):
    summary_rows.append({
        "Model": model_name,
        "Source Acc (%)": mean_std_percent(group["source_accuracy"]),
        "Zero-shot Acc (%)": mean_std_percent(group["zero_shot_accuracy"]),
        "Fine-tuned Acc (%)": mean_std_percent(group["finetuned_accuracy"]),
        "Zero-shot Drop (%)": mean_std_percent(group["zero_shot_drop"]),
        "Fine-tuned Drop (%)": mean_std_percent(group["finetuned_drop"]),
        "Zero-shot Ratio": mean_std_ratio(group["zero_shot_ratio"]),
        "Fine-tuned Ratio": mean_std_ratio(group["finetuned_ratio"]),
        "Source Macro F1": mean_std_ratio(group["source_macro_f1"]),
        "Zero-shot Macro F1": mean_std_ratio(group["zero_shot_macro_f1"]),
        "Fine-tuned Macro F1": mean_std_ratio(group["finetuned_macro_f1"]),
        "Source Weighted F1": mean_std_ratio(group["source_weighted_f1"]),
        "Zero-shot Weighted F1": mean_std_ratio(group["zero_shot_weighted_f1"]),
        "Fine-tuned Weighted F1": mean_std_ratio(group["finetuned_weighted_f1"])
    })

summary_df = pd.DataFrame(summary_rows)

summary_path = os.path.join(OUTPUT_DIR, "cross_dataset_transfer_results.csv")
summary_df.to_csv(summary_path, index=False)

print("Saved summary results to:", summary_path)
summary_df

Saved summary results to: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_results.csv

,Model,Source Acc (%),Zero-shot Acc (%),Fine-tuned Acc (%),Zero-shot Drop (%),Fine-tuned Drop (%),Zero-shot Ratio,Fine-tuned Ratio,Source Macro F1,Zero-shot Macro F1,Fine-tuned Macro F1,Source Weighted F1,Zero-shot Weighted F1,Fine-tuned Weighted F1
0,EfficientNetB0,99.54 ± 0.41,91.73 ± 1.16,98.93 ± 1.16,7.80 ± 1.46,0.60 ± 1.46,0.9216 ± 0.0144,0.9940 ± 0.0146,0.9885 ± 0.0103,0.9166 ± 0.0122,0.9893 ± 0.0117,0.9955 ± 0.0040,0.9166 ± 0.0122,0.9893 ± 0.0117
1,Lightweight CNN,89.81 ± 2.38,65.87 ± 6.67,87.87 ± 2.54,23.95 ± 7.39,1.95 ± 3.87,0.7342 ± 0.0805,0.9792 ± 0.0415,0.8665 ± 0.0280,0.6517 ± 0.0779,0.8783 ± 0.0256,0.9003 ± 0.0236,0.6517 ± 0.0779,0.8783 ± 0.0256
2,MobileNetV2,98.52 ± 0.74,85.73 ± 3.47,95.07 ± 3.09,12.79 ± 3.69,3.45 ± 3.33,0.8703 ± 0.0370,0.9651 ± 0.0338,0.9642 ± 0.0175,0.8540 ± 0.0354,0.9499 ± 0.0316,0.9854 ± 0.0073,0.8540 ± 0.0354,0.9499 ± 0.0316

In [35]:
paper_table = summary_df[
    [
        "Model",
        "Source Acc (%)",
        "Zero-shot Acc (%)",
        "Fine-tuned Acc (%)",
        "Zero-shot Drop (%)",
        "Fine-tuned Drop (%)",
        "Zero-shot Ratio",
        "Fine-tuned Ratio"
    ]
]

paper_table_path = os.path.join(OUTPUT_DIR, "cross_dataset_transfer_paper_table.csv")
paper_table.to_csv(paper_table_path, index=False)

print("Saved paper table to:", paper_table_path)
paper_table

Saved paper table to: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_paper_table.csv

,Model,Source Acc (%),Zero-shot Acc (%),Fine-tuned Acc (%),Zero-shot Drop (%),Fine-tuned Drop (%),Zero-shot Ratio,Fine-tuned Ratio
0,EfficientNetB0,99.54 ± 0.41,91.73 ± 1.16,98.93 ± 1.16,7.80 ± 1.46,0.60 ± 1.46,0.9216 ± 0.0144,0.9940 ± 0.0146
1,Lightweight CNN,89.81 ± 2.38,65.87 ± 6.67,87.87 ± 2.54,23.95 ± 7.39,1.95 ± 3.87,0.7342 ± 0.0805,0.9792 ± 0.0415
2,MobileNetV2,98.52 ± 0.74,85.73 ± 3.47,95.07 ± 3.09,12.79 ± 3.69,3.45 ± 3.33,0.8703 ± 0.0370,0.9651 ± 0.0338

In [36]:
zip_name = f"{OUTPUT_DIR}.zip"

!zip -r {zip_name} {OUTPUT_DIR}

print("Created:", zip_name)

  adding: cross_dataset_transfer_20260530-210441/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_per_seed_results.csv (deflated 77%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_paper_table.csv (deflated 46%)
  adding: cross_dataset_transfer_20260530-210441/histories/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_target_finetune_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_target_finetune_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_source_history.pkl (deflated 50%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_target_finetune_history.pkl (deflated 64%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_source_history.pkl (deflated 50%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_source_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_target_finetune_history.pkl (deflated 61%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_target_finetune_history.pkl (deflated 44%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_target_finetune_history.pkl (deflated 60%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_target_finetune_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_target_finetune_history.pkl (deflated 45%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_target_finetune_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_results.csv (deflated 59%)
  adding: cross_dataset_transfer_20260530-210441/models/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_source.keras (deflated 14%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_source.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_source.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_target_finetuned.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_source.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_target_finetuned.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_source.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/reports/ (stored 0%)
Created: cross_dataset_transfer_20260530-210441.zip

In [38]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [39]:
PREDICTION_FILES = {
    ("Lightweight CNN", "3-class"): "/kaggle/working/path/to/lightweight_cnn_3class_predictions.csv",
    ("Lightweight CNN", "7-class"): "/kaggle/working/path/to/lightweight_cnn_7class_predictions.csv",

    ("MobileNetV2", "3-class"): "/kaggle/working/path/to/mobilenetv2_3class_predictions.csv",
    ("MobileNetV2", "7-class"): "/kaggle/working/path/to/mobilenetv2_7class_predictions.csv",

    ("EfficientNetB0", "3-class"): "/kaggle/working/path/to/efficientnetb0_3class_predictions.csv",
    ("EfficientNetB0", "7-class"): "/kaggle/working/path/to/efficientnetb0_7class_predictions.csv",
}

In [41]:
import os

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.endswith(".csv") and ("prediction" in file.lower() or "test_predictions" in file.lower()):
            print(os.path.join(root, file))

In [42]:
for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_per_seed_results.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_paper_table.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_results.csv

In [40]:
required_columns = [
    "image_path",
    "true_class",
    "pred_class",
    "confidence",
    "correct"
]

prediction_dfs = {}

for (model_name, dataset_name), csv_path in PREDICTION_FILES.items():
    if not os.path.exists(csv_path):
        print(f"Missing file: {csv_path}")
        continue

    df = pd.read_csv(csv_path)

    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(
            f"{csv_path} is missing columns: {missing_cols}"
        )

    df = df.copy()
    df["confidence"] = df["confidence"].astype(float)

    if df["correct"].dtype != bool:
        df["correct"] = df["correct"].astype(str).str.lower().isin(["true", "1", "yes"])

    prediction_dfs[(model_name, dataset_name)] = df

    print(f"Loaded {model_name} | {dataset_name}: {len(df)} samples")

Missing file: /kaggle/working/path/to/lightweight_cnn_3class_predictions.csv
Missing file: /kaggle/working/path/to/lightweight_cnn_7class_predictions.csv
Missing file: /kaggle/working/path/to/mobilenetv2_3class_predictions.csv
Missing file: /kaggle/working/path/to/mobilenetv2_7class_predictions.csv
Missing file: /kaggle/working/path/to/efficientnetb0_3class_predictions.csv
Missing file: /kaggle/working/path/to/efficientnetb0_7class_predictions.csv

In [43]:
import os

BASE_DIR = "/kaggle/working/cross_dataset_transfer_20260530-210441"

print("All files inside:", BASE_DIR)
for root, dirs, files in os.walk(BASE_DIR):
    for file in files:
        print(os.path.join(root, file))

All files inside: /kaggle/working/cross_dataset_transfer_20260530-210441
/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_per_seed_results.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_paper_table.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/cross_dataset_transfer_results.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_source_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_target_finetune_history.pkl
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_target_finetuned.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_source.keras
/kaggle/working/cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_target_finetuned.keras

In [45]:
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocess
from sklearn.model_selection import train_test_split

BASE_DIR = "/kaggle/working/cross_dataset_transfer_20260530-210441"

CANONICAL_CLASSES = ["Early Blight", "Late Blight", "Healthy"]
NUM_CLASSES = 3

SEEDS = [42, 123, 2024, 3407, 777]

# Use the same dataset paths from your transfer experiment
SOURCE_DATASET_DIR = "/kaggle/input/datasets/faysalmiah1721758/potato-dataset"
TARGET_DATASET_DIR = "/kaggle/input/datasets/shahadhossin567r7455/potato-leaf-disease-dataset/Potato Leaf DIsease"

CLASS_FOLDER_CANDIDATES = {
    "Early Blight": ["Early Blight", "Early_Blight", "Potato___Early_blight"],
    "Late Blight": ["Late Blight", "Late_Blight", "Potato___Late_blight"],
    "Healthy": ["Healthy", "healthy", "Potato___healthy"]
}

def find_class_folder(dataset_dir, canonical_class):
    folders = [
        folder for folder in os.listdir(dataset_dir)
        if os.path.isdir(os.path.join(dataset_dir, folder))
    ]

    for candidate in CLASS_FOLDER_CANDIDATES[canonical_class]:
        if candidate in folders:
            return os.path.join(dataset_dir, candidate)

    raise ValueError(f"Could not find {canonical_class}. Available folders: {folders}")

def collect_paths_and_labels(dataset_dir):
    valid_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

    file_paths = []
    labels = []

    for label_index, class_name in enumerate(CANONICAL_CLASSES):
        class_dir = find_class_folder(dataset_dir, class_name)

        for fname in os.listdir(class_dir):
            if fname.lower().endswith(valid_extensions):
                file_paths.append(os.path.join(class_dir, fname))
                labels.append(label_index)

    return np.array(file_paths), np.array(labels)

def make_splits(file_paths, labels, seed):
    X_train, X_temp, y_train, y_temp = train_test_split(
        file_paths,
        labels,
        test_size=0.20,
        stratify=labels,
        random_state=seed
    )

    X_val, X_test, y_val, y_test = train_test_split(
        X_temp,
        y_temp,
        test_size=0.50,
        stratify=y_temp,
        random_state=seed
    )

    return X_train, X_val, X_test, y_train, y_val, y_test

def cnn_preprocess(image):
    return image / 255.0

MODEL_SETTINGS = {
    "Lightweight_CNN": {
        "display_name": "Lightweight CNN",
        "image_size": (256, 256),
        "preprocess_fn": cnn_preprocess
    },
    "MobileNetV2": {
        "display_name": "MobileNetV2",
        "image_size": (224, 224),
        "preprocess_fn": mobilenet_preprocess
    },
    "EfficientNetB0": {
        "display_name": "EfficientNetB0",
        "image_size": (224, 224),
        "preprocess_fn": efficientnet_preprocess
    }
}

def load_image_for_prediction(image_path, image_size, preprocess_fn):
    image_raw = tf.io.read_file(image_path)
    image = tf.image.decode_image(image_raw, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])

    image = tf.image.resize(image, image_size)
    image = tf.cast(image, tf.float32)

    image = preprocess_fn(image)
    image = tf.expand_dims(image, axis=0)

    return image

def generate_prediction_csv(model_path, file_paths, labels, model_key, dataset_name, seed, output_dir):
    model = load_model(model_path)

    image_size = MODEL_SETTINGS[model_key]["image_size"]
    preprocess_fn = MODEL_SETTINGS[model_key]["preprocess_fn"]

    records = []

    for image_path, true_label in zip(file_paths, labels):
        image = load_image_for_prediction(image_path, image_size, preprocess_fn)
        probs = model.predict(image, verbose=0)[0]

        pred_label = int(np.argmax(probs))
        confidence = float(np.max(probs))

        records.append({
            "image_path": image_path,
            "true_label": int(true_label),
            "true_class": CANONICAL_CLASSES[int(true_label)],
            "predicted_label": pred_label,
            "pred_class": CANONICAL_CLASSES[pred_label],
            "confidence": confidence,
            "correct": int(true_label) == pred_label,
            "model": MODEL_SETTINGS[model_key]["display_name"],
            "dataset": dataset_name,
            "seed": seed
        })

    pred_df = pd.DataFrame(records)

    os.makedirs(output_dir, exist_ok=True)

    csv_path = os.path.join(
        output_dir,
        f"test_predictions_{model_key}_{dataset_name}_seed_{seed}.csv"
    )

    pred_df.to_csv(csv_path, index=False)

    print("Saved:", csv_path)

    return csv_path

In [46]:
source_paths, source_labels = collect_paths_and_labels(SOURCE_DATASET_DIR)
target_paths, target_labels = collect_paths_and_labels(TARGET_DATASET_DIR)

prediction_output_dir = os.path.join(BASE_DIR, "prediction_csvs")
generated_prediction_files = []

for model_key in ["Lightweight_CNN", "MobileNetV2", "EfficientNetB0"]:
    for seed in SEEDS:
        _, _, source_test, _, _, y_source_test = make_splits(
            source_paths,
            source_labels,
            seed
        )

        _, _, target_test, _, _, y_target_test = make_splits(
            target_paths,
            target_labels,
            seed
        )

        source_model_path = os.path.join(
            BASE_DIR,
            "models",
            f"{model_key}_seed_{seed}_source.keras"
        )

        target_model_path = os.path.join(
            BASE_DIR,
            "models",
            f"{model_key}_seed_{seed}_target_finetuned.keras"
        )

        if os.path.exists(source_model_path):
            generated_prediction_files.append(
                generate_prediction_csv(
                    model_path=source_model_path,
                    file_paths=source_test,
                    labels=y_source_test,
                    model_key=model_key,
                    dataset_name="source_3class",
                    seed=seed,
                    output_dir=prediction_output_dir
                )
            )

            generated_prediction_files.append(
                generate_prediction_csv(
                    model_path=source_model_path,
                    file_paths=target_test,
                    labels=y_target_test,
                    model_key=model_key,
                    dataset_name="zero_shot_target_3class",
                    seed=seed,
                    output_dir=prediction_output_dir
                )
            )

        if os.path.exists(target_model_path):
            generated_prediction_files.append(
                generate_prediction_csv(
                    model_path=target_model_path,
                    file_paths=target_test,
                    labels=y_target_test,
                    model_key=model_key,
                    dataset_name="finetuned_target_3class",
                    seed=seed,
                    output_dir=prediction_output_dir
                )
            )

print("Generated prediction files:")
for path in generated_prediction_files:
    print(path)

Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_42.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_123.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_2024.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_3407.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_777.csv
Saved: /kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_777.csv
Generated prediction files:
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_777.csv

In [47]:
for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if file.endswith(".csv") and "test_predictions" in file:
            print(os.path.join(root, file))

/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_2024.csv

In [48]:
prediction_files = []

for root, dirs, files in os.walk("/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs"):
    for file in files:
        if file.endswith(".csv") and file.startswith("test_predictions"):
            prediction_files.append(os.path.join(root, file))

print("Found prediction files:", len(prediction_files))

for path in prediction_files:
    print(path)

Found prediction files: 45
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_777.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_123.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_42.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_2024.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_3407.csv
/kaggle/working/cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_2024.csv

In [49]:
required_columns = [
    "image_path",
    "true_class",
    "pred_class",
    "confidence",
    "correct",
    "model",
    "dataset",
    "seed"
]

prediction_dfs = []

for csv_path in prediction_files:
    df = pd.read_csv(csv_path)

    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(f"{csv_path} missing columns: {missing_cols}")

    df["confidence"] = df["confidence"].astype(float)

    if df["correct"].dtype != bool:
        df["correct"] = df["correct"].astype(str).str.lower().isin(["true", "1", "yes"])

    prediction_dfs.append(df)

all_predictions_df = pd.concat(prediction_dfs, ignore_index=True)

print("Total prediction rows:", len(all_predictions_df))
display(all_predictions_df.head())

Total prediction rows: 7740

,image_path,true_label,true_class,predicted_label,pred_class,confidence,correct,model,dataset,seed
0,/kaggle/input/datasets/shahadhossin567r7455/po...,1,Late Blight,1,Late Blight,0.840941,True,MobileNetV2,finetuned_target_3class,42
1,/kaggle/input/datasets/shahadhossin567r7455/po...,0,Early Blight,0,Early Blight,0.999999,True,MobileNetV2,finetuned_target_3class,42
2,/kaggle/input/datasets/shahadhossin567r7455/po...,2,Healthy,2,Healthy,0.995557,True,MobileNetV2,finetuned_target_3class,42
3,/kaggle/input/datasets/shahadhossin567r7455/po...,2,Healthy,2,Healthy,0.999999,True,MobileNetV2,finetuned_target_3class,42
4,/kaggle/input/datasets/shahadhossin567r7455/po...,2,Healthy,2,Healthy,0.998354,True,MobileNetV2,finetuned_target_3class,42

In [50]:
def compute_decision_metrics(df, scheme_name, alpha=None, beta=None):
    total_samples = len(df)
    total_wrong = (~df["correct"]).sum()

    accept_df = df[df["decision_region"] == "Accept"]
    defer_df = df[df["decision_region"] == "Defer"]
    reject_df = df[df["decision_region"] == "Reject"]

    accept_count = len(accept_df)
    defer_count = len(defer_df)
    reject_count = len(reject_df)

    accept_percentage = accept_count / total_samples * 100
    defer_percentage = defer_count / total_samples * 100
    reject_percentage = reject_count / total_samples * 100

    if accept_count > 0:
        accept_accuracy = accept_df["correct"].mean() * 100
    else:
        accept_accuracy = np.nan

    captured_wrong = df[
        (~df["correct"]) &
        (df["decision_region"].isin(["Defer", "Reject"]))
    ]

    if total_wrong > 0:
        wrong_capture_rate = len(captured_wrong) / total_wrong * 100
    else:
        wrong_capture_rate = np.nan

    return {
        "scheme": scheme_name,
        "alpha": alpha,
        "beta": beta,
        "total_samples": total_samples,
        "accept_count": accept_count,
        "defer_count": defer_count,
        "reject_count": reject_count,
        "accept_percentage": accept_percentage,
        "defer_percentage": defer_percentage,
        "reject_percentage": reject_percentage,
        "accept_accuracy": accept_accuracy,
        "wrong_capture_rate": wrong_capture_rate,
        "total_wrong": int(total_wrong),
        "captured_wrong": int(len(captured_wrong))
    }

In [51]:
two_way_alphas = [0.85, 0.90, 0.95]

three_way_thresholds = [
    (0.95, 0.70),
    (0.90, 0.60),
    (0.85, 0.50)
]

ablation_rows = []

group_cols = ["model", "dataset", "seed"]

for (model_name, dataset_name, seed), group_df in all_predictions_df.groupby(group_cols):
    group_df = group_df.copy()

    # A. Standard hard prediction
    standard_df = group_df.copy()
    standard_df["decision_region"] = "Accept"

    result = compute_decision_metrics(
        standard_df,
        scheme_name="Standard",
        alpha=None,
        beta=None
    )
    result["model"] = model_name
    result["dataset"] = dataset_name
    result["seed"] = seed
    ablation_rows.append(result)

    # B. Two-way decision
    for alpha in two_way_alphas:
        two_way_df = group_df.copy()
        two_way_df["decision_region"] = np.where(
            two_way_df["confidence"] >= alpha,
            "Accept",
            "Reject"
        )

        result = compute_decision_metrics(
            two_way_df,
            scheme_name="Two-way",
            alpha=alpha,
            beta=None
        )
        result["model"] = model_name
        result["dataset"] = dataset_name
        result["seed"] = seed
        ablation_rows.append(result)

    # C. Three-way decision
    for alpha, beta in three_way_thresholds:
        three_way_df = group_df.copy()

        conditions = [
            three_way_df["confidence"] >= alpha,
            (three_way_df["confidence"] >= beta) & (three_way_df["confidence"] < alpha),
            three_way_df["confidence"] < beta
        ]

        choices = ["Accept", "Defer", "Reject"]

        three_way_df["decision_region"] = np.select(
            conditions,
            choices,
            default="Reject"
        )

        result = compute_decision_metrics(
            three_way_df,
            scheme_name="Three-way",
            alpha=alpha,
            beta=beta
        )
        result["model"] = model_name
        result["dataset"] = dataset_name
        result["seed"] = seed
        ablation_rows.append(result)

ablation_df = pd.DataFrame(ablation_rows)

ablation_df = ablation_df[
    [
        "model",
        "dataset",
        "seed",
        "scheme",
        "alpha",
        "beta",
        "total_samples",
        "accept_count",
        "defer_count",
        "reject_count",
        "accept_percentage",
        "defer_percentage",
        "reject_percentage",
        "accept_accuracy",
        "wrong_capture_rate",
        "total_wrong",
        "captured_wrong"
    ]
]

ablation_results_path = "ablation_decision_mechanism_results.csv"
ablation_df.to_csv(ablation_results_path, index=False)

print("Saved:", ablation_results_path)
display(ablation_df.head())

Saved: ablation_decision_mechanism_results.csv

,model,dataset,seed,scheme,alpha,beta,total_samples,accept_count,defer_count,reject_count,accept_percentage,defer_percentage,reject_percentage,accept_accuracy,wrong_capture_rate,total_wrong,captured_wrong
0,EfficientNetB0,finetuned_target_3class,42,Standard,NaN,NaN,150,150,0,0,100.000000,0.0,0.000000,96.666667,0.0,5,0
1,EfficientNetB0,finetuned_target_3class,42,Two-way,0.85,NaN,150,145,0,5,96.666667,0.0,3.333333,99.310345,80.0,5,4
2,EfficientNetB0,finetuned_target_3class,42,Two-way,0.90,NaN,150,144,0,6,96.000000,0.0,4.000000,99.305556,80.0,5,4
3,EfficientNetB0,finetuned_target_3class,42,Two-way,0.95,NaN,150,140,0,10,93.333333,0.0,6.666667,100.000000,100.0,5,5
4,EfficientNetB0,finetuned_target_3class,42,Three-way,0.95,0.7,150,140,6,4,93.333333,4.0,2.666667,100.000000,100.0,5,5

In [52]:
summary_metrics = [
    "accept_percentage",
    "defer_percentage",
    "reject_percentage",
    "accept_accuracy",
    "wrong_capture_rate"
]

summary_rows = []

for keys, group in ablation_df.groupby(["model", "dataset", "scheme", "alpha", "beta"], dropna=False):
    model_name, dataset_name, scheme, alpha, beta = keys

    row = {
        "model": model_name,
        "dataset": dataset_name,
        "scheme": scheme,
        "alpha": alpha,
        "beta": beta
    }

    for metric in summary_metrics:
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_std"] = group[metric].std(ddof=0)

    summary_rows.append(row)

ablation_summary_df = pd.DataFrame(summary_rows)

ablation_summary_path = "ablation_decision_mechanism_summary_mean_std.csv"
ablation_summary_df.to_csv(ablation_summary_path, index=False)

print("Saved:", ablation_summary_path)
display(ablation_summary_df.head())

Saved: ablation_decision_mechanism_summary_mean_std.csv

,model,dataset,scheme,alpha,beta,accept_percentage_mean,accept_percentage_std,defer_percentage_mean,defer_percentage_std,reject_percentage_mean,reject_percentage_std,accept_accuracy_mean,accept_accuracy_std,wrong_capture_rate_mean,wrong_capture_rate_std
0,EfficientNetB0,finetuned_target_3class,Standard,NaN,NaN,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,98.933333,1.162373,0.0,0.000000
1,EfficientNetB0,finetuned_target_3class,Three-way,0.85,0.5,96.800000,0.498888,3.066667,0.533333,0.133333,0.266667,99.862069,0.275862,95.0,8.660254
2,EfficientNetB0,finetuned_target_3class,Three-way,0.90,0.6,95.866667,1.066667,3.200000,1.146977,0.933333,0.679869,99.861111,0.277778,95.0,8.660254
3,EfficientNetB0,finetuned_target_3class,Three-way,0.95,0.7,93.466667,1.707500,5.066667,1.717880,1.466667,0.653197,100.000000,0.000000,100.0,0.000000
4,EfficientNetB0,finetuned_target_3class,Two-way,0.85,NaN,96.800000,0.498888,0.000000,0.000000,3.200000,0.498888,99.862069,0.275862,95.0,8.660254

In [53]:
table_a = ablation_summary_df[
    (
        (ablation_summary_df["scheme"] == "Standard") |
        (
            (ablation_summary_df["scheme"] == "Two-way") &
            (ablation_summary_df["alpha"] == 0.90)
        ) |
        (
            (ablation_summary_df["scheme"] == "Three-way") &
            (ablation_summary_df["alpha"] == 0.90) &
            (ablation_summary_df["beta"] == 0.60)
        )
    )
].copy()

def format_mean_std(row, metric):
    return f"{row[f'{metric}_mean']:.2f} ± {row[f'{metric}_std']:.2f}"

table_a["setting"] = table_a.apply(
    lambda row: (
        "Standard"
        if row["scheme"] == "Standard"
        else "Two-way α=0.90"
        if row["scheme"] == "Two-way"
        else "Three-way α=0.90, β=0.60"
    ),
    axis=1
)

table_a_formatted = pd.DataFrame({
    "Model": table_a["model"],
    "Dataset": table_a["dataset"],
    "Setting": table_a["setting"],
    "Accept (%)": table_a.apply(lambda row: format_mean_std(row, "accept_percentage"), axis=1),
    "Defer (%)": table_a.apply(lambda row: format_mean_std(row, "defer_percentage"), axis=1),
    "Reject (%)": table_a.apply(lambda row: format_mean_std(row, "reject_percentage"), axis=1),
    "Accept Accuracy (%)": table_a.apply(lambda row: format_mean_std(row, "accept_accuracy"), axis=1),
    "Wrong Capture Rate (%)": table_a.apply(lambda row: format_mean_std(row, "wrong_capture_rate"), axis=1)
})

table_a_formatted = table_a_formatted.sort_values(["Dataset", "Model", "Setting"])

table_a_path = "ablation_table_A_standard_two_way_three_way.csv"
table_a_formatted.to_csv(table_a_path, index=False)

print("Saved:", table_a_path)
display(table_a_formatted)

Saved: ablation_table_A_standard_two_way_three_way.csv

,Model,Dataset,Setting,Accept (%),Defer (%),Reject (%),Accept Accuracy (%),Wrong Capture Rate (%)
0,EfficientNetB0,finetuned_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,98.93 ± 1.16,0.00 ± 0.00
2,EfficientNetB0,finetuned_target_3class,"Three-way α=0.90, β=0.60",95.87 ± 1.07,3.20 ± 1.15,0.93 ± 0.68,99.86 ± 0.28,95.00 ± 8.66
5,EfficientNetB0,finetuned_target_3class,Two-way α=0.90,95.87 ± 1.07,0.00 ± 0.00,4.13 ± 1.07,99.86 ± 0.28,95.00 ± 8.66
21,Lightweight CNN,finetuned_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,87.87 ± 2.54,0.00 ± 0.00
23,Lightweight CNN,finetuned_target_3class,"Three-way α=0.90, β=0.60",51.47 ± 3.54,37.60 ± 2.00,10.93 ± 2.69,98.49 ± 1.46,93.64 ± 6.05
26,Lightweight CNN,finetuned_target_3class,Two-way α=0.90,51.47 ± 3.54,0.00 ± 0.00,48.53 ± 3.54,98.49 ± 1.46,93.64 ± 6.05
42,MobileNetV2,finetuned_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,95.07 ± 3.09,0.00 ± 0.00
44,MobileNetV2,finetuned_target_3class,"Three-way α=0.90, β=0.60",91.87 ± 3.80,6.53 ± 3.80,1.60 ± 1.08,97.77 ± 1.95,68.47 ± 20.80
47,MobileNetV2,finetuned_target_3class,Two-way α=0.90,91.87 ± 3.80,0.00 ± 0.00,8.13 ± 3.80,97.77 ± 1.95,68.47 ± 20.80
7,EfficientNetB0,source_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,99.54 ± 0.41,0.00 ± 0.00
9,EfficientNetB0,source_3class,"Three-way α=0.90, β=0.60",94.07 ± 1.15,4.91 ± 0.95,1.02 ± 0.68,99.90 ± 0.20,83.33 ± 23.57
12,EfficientNetB0,source_3class,Two-way α=0.90,94.07 ± 1.15,0.00 ± 0.00,5.93 ± 1.15,99.90 ± 0.20,83.33 ± 23.57
28,Lightweight CNN,source_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,89.81 ± 2.38,0.00 ± 0.00
30,Lightweight CNN,source_3class,"Three-way α=0.90, β=0.60",51.85 ± 9.32,37.78 ± 8.40,10.37 ± 1.26,99.00 ± 0.90,95.17 ± 4.79
33,Lightweight CNN,source_3class,Two-way α=0.90,51.85 ± 9.32,0.00 ± 0.00,48.15 ± 9.32,99.00 ± 0.90,95.17 ± 4.79
49,MobileNetV2,source_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,98.52 ± 0.74,0.00 ± 0.00
51,MobileNetV2,source_3class,"Three-way α=0.90, β=0.60",95.74 ± 1.03,3.61 ± 0.90,0.65 ± 0.23,99.51 ± 0.31,61.33 ± 33.57
54,MobileNetV2,source_3class,Two-way α=0.90,95.74 ± 1.03,0.00 ± 0.00,4.26 ± 1.03,99.51 ± 0.31,61.33 ± 33.57
14,EfficientNetB0,zero_shot_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,91.73 ± 1.16,0.00 ± 0.00
16,EfficientNetB0,zero_shot_target_3class,"Three-way α=0.90, β=0.60",75.20 ± 2.17,13.73 ± 0.68,11.07 ± 1.61,99.82 ± 0.36,98.67 ± 2.67
19,EfficientNetB0,zero_shot_target_3class,Two-way α=0.90,75.20 ± 2.17,0.00 ± 0.00,24.80 ± 2.17,99.82 ± 0.36,98.67 ± 2.67
35,Lightweight CNN,zero_shot_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,65.87 ± 6.67,0.00 ± 0.00
37,Lightweight CNN,zero_shot_target_3class,"Three-way α=0.90, β=0.60",39.33 ± 9.27,46.93 ± 5.81,13.73 ± 4.31,78.64 ± 11.15,74.72 ± 12.17
40,Lightweight CNN,zero_shot_target_3class,Two-way α=0.90,39.33 ± 9.27,0.00 ± 0.00,60.67 ± 9.27,78.64 ± 11.15,74.72 ± 12.17
56,MobileNetV2,zero_shot_target_3class,Standard,100.00 ± 0.00,0.00 ± 0.00,0.00 ± 0.00,85.73 ± 3.47,0.00 ± 0.00
58,MobileNetV2,zero_shot_target_3class,"Three-way α=0.90, β=0.60",77.33 ± 4.17,14.40 ± 3.69,8.27 ± 1.87,96.72 ± 1.03,82.33 ± 3.45
61,MobileNetV2,zero_shot_target_3class,Two-way α=0.90,77.33 ± 4.17,0.00 ± 0.00,22.67 ± 4.17,96.72 ± 1.03,82.33 ± 3.45

In [54]:
table_b = ablation_summary_df[
    ablation_summary_df["scheme"] == "Three-way"
].copy()

table_b["threshold_pair"] = table_b.apply(
    lambda row: f"α={row['alpha']:.2f}, β={row['beta']:.2f}",
    axis=1
)

table_b_formatted = pd.DataFrame({
    "Model": table_b["model"],
    "Dataset": table_b["dataset"],
    "Threshold Pair": table_b["threshold_pair"],
    "Accept (%)": table_b.apply(lambda row: format_mean_std(row, "accept_percentage"), axis=1),
    "Defer (%)": table_b.apply(lambda row: format_mean_std(row, "defer_percentage"), axis=1),
    "Reject (%)": table_b.apply(lambda row: format_mean_std(row, "reject_percentage"), axis=1),
    "Accept Accuracy (%)": table_b.apply(lambda row: format_mean_std(row, "accept_accuracy"), axis=1),
    "Wrong Capture Rate (%)": table_b.apply(lambda row: format_mean_std(row, "wrong_capture_rate"), axis=1)
})

table_b_formatted = table_b_formatted.sort_values(["Dataset", "Model", "Threshold Pair"])

threshold_results_path = "ablation_threshold_sensitivity_results.csv"
table_b_formatted.to_csv(threshold_results_path, index=False)

print("Saved:", threshold_results_path)
display(table_b_formatted)

Saved: ablation_threshold_sensitivity_results.csv

,Model,Dataset,Threshold Pair,Accept (%),Defer (%),Reject (%),Accept Accuracy (%),Wrong Capture Rate (%)
1,EfficientNetB0,finetuned_target_3class,"α=0.85, β=0.50",96.80 ± 0.50,3.07 ± 0.53,0.13 ± 0.27,99.86 ± 0.28,95.00 ± 8.66
2,EfficientNetB0,finetuned_target_3class,"α=0.90, β=0.60",95.87 ± 1.07,3.20 ± 1.15,0.93 ± 0.68,99.86 ± 0.28,95.00 ± 8.66
3,EfficientNetB0,finetuned_target_3class,"α=0.95, β=0.70",93.47 ± 1.71,5.07 ± 1.72,1.47 ± 0.65,100.00 ± 0.00,100.00 ± 0.00
22,Lightweight CNN,finetuned_target_3class,"α=0.85, β=0.50",61.33 ± 2.76,35.33 ± 2.39,3.33 ± 0.42,97.41 ± 1.57,87.49 ± 5.66
23,Lightweight CNN,finetuned_target_3class,"α=0.90, β=0.60",51.47 ± 3.54,37.60 ± 2.00,10.93 ± 2.69,98.49 ± 1.46,93.64 ± 6.05
24,Lightweight CNN,finetuned_target_3class,"α=0.95, β=0.70",32.00 ± 6.75,49.33 ± 4.64,18.67 ± 3.18,98.87 ± 1.42,96.90 ± 3.81
43,MobileNetV2,finetuned_target_3class,"α=0.85, β=0.50",92.53 ± 4.07,7.20 ± 4.22,0.27 ± 0.33,97.49 ± 1.92,64.02 ± 20.71
44,MobileNetV2,finetuned_target_3class,"α=0.90, β=0.60",91.87 ± 3.80,6.53 ± 3.80,1.60 ± 1.08,97.77 ± 1.95,68.47 ± 20.80
45,MobileNetV2,finetuned_target_3class,"α=0.95, β=0.70",88.53 ± 4.80,7.60 ± 3.54,3.87 ± 1.60,98.27 ± 1.30,75.46 ± 13.14
8,EfficientNetB0,source_3class,"α=0.85, β=0.50",96.30 ± 0.72,3.70 ± 0.72,0.00 ± 0.00,99.81 ± 0.38,66.67 ± 47.14
9,EfficientNetB0,source_3class,"α=0.90, β=0.60",94.07 ± 1.15,4.91 ± 0.95,1.02 ± 0.68,99.90 ± 0.20,83.33 ± 23.57
10,EfficientNetB0,source_3class,"α=0.95, β=0.70",89.54 ± 2.28,8.70 ± 2.29,1.76 ± 0.74,99.90 ± 0.21,83.33 ± 23.57
29,Lightweight CNN,source_3class,"α=0.85, β=0.50",63.61 ± 6.21,35.28 ± 6.11,1.11 ± 0.47,98.85 ± 0.88,92.94 ± 5.39
30,Lightweight CNN,source_3class,"α=0.90, β=0.60",51.85 ± 9.32,37.78 ± 8.40,10.37 ± 1.26,99.00 ± 0.90,95.17 ± 4.79
31,Lightweight CNN,source_3class,"α=0.95, β=0.70",35.93 ± 9.41,44.81 ± 6.79,19.26 ± 3.27,99.36 ± 0.80,97.53 ± 3.24
50,MobileNetV2,source_3class,"α=0.85, β=0.50",96.67 ± 1.03,3.33 ± 1.03,0.00 ± 0.00,99.52 ± 0.31,61.33 ± 33.57
51,MobileNetV2,source_3class,"α=0.90, β=0.60",95.74 ± 1.03,3.61 ± 0.90,0.65 ± 0.23,99.51 ± 0.31,61.33 ± 33.57
52,MobileNetV2,source_3class,"α=0.95, β=0.70",93.24 ± 1.84,5.56 ± 1.40,1.20 ± 0.56,99.60 ± 0.20,65.33 ± 34.36
15,EfficientNetB0,zero_shot_target_3class,"α=0.85, β=0.50",78.27 ± 1.72,15.47 ± 1.86,6.27 ± 1.00,99.50 ± 0.41,95.13 ± 4.12
16,EfficientNetB0,zero_shot_target_3class,"α=0.90, β=0.60",75.20 ± 2.17,13.73 ± 0.68,11.07 ± 1.61,99.82 ± 0.36,98.67 ± 2.67
17,EfficientNetB0,zero_shot_target_3class,"α=0.95, β=0.70",68.27 ± 1.55,16.27 ± 1.37,15.47 ± 1.54,100.00 ± 0.00,100.00 ± 0.00
36,Lightweight CNN,zero_shot_target_3class,"α=0.85, β=0.50",49.73 ± 9.86,48.53 ± 9.72,1.73 ± 1.37,75.89 ± 9.23,64.71 ± 11.84
37,Lightweight CNN,zero_shot_target_3class,"α=0.90, β=0.60",39.33 ± 9.27,46.93 ± 5.81,13.73 ± 4.31,78.64 ± 11.15,74.72 ± 12.17
38,Lightweight CNN,zero_shot_target_3class,"α=0.95, β=0.70",24.67 ± 10.36,50.27 ± 5.60,25.07 ± 4.89,84.42 ± 9.30,87.56 ± 8.33
57,MobileNetV2,zero_shot_target_3class,"α=0.85, β=0.50",80.80 ± 3.28,15.73 ± 3.49,3.47 ± 0.78,95.19 ± 0.78,71.53 ± 6.72
58,MobileNetV2,zero_shot_target_3class,"α=0.90, β=0.60",77.33 ± 4.17,14.40 ± 3.69,8.27 ± 1.87,96.72 ± 1.03,82.33 ± 3.45
59,MobileNetV2,zero_shot_target_3class,"α=0.95, β=0.70",70.67 ± 4.11,17.20 ± 3.22,12.13 ± 1.86,98.31 ± 1.10,92.29 ± 4.73

In [55]:
!zip -r ablation_decision_mechanism_outputs.zip \
ablation_decision_mechanism_results.csv \
ablation_decision_mechanism_summary_mean_std.csv \
ablation_table_A_standard_two_way_three_way.csv \
ablation_threshold_sensitivity_results.csv

print("Created: ablation_decision_mechanism_outputs.zip")

  adding: ablation_decision_mechanism_results.csv (deflated 87%)
  adding: ablation_decision_mechanism_summary_mean_std.csv (deflated 77%)
  adding: ablation_table_A_standard_two_way_three_way.csv (deflated 77%)
  adding: ablation_threshold_sensitivity_results.csv (deflated 70%)
Created: ablation_decision_mechanism_outputs.zip

In [56]:
table_b_main = table_b_formatted[
    table_b_formatted["Dataset"].str.contains("7", case=False, na=False)
].copy()

table_b_main_path = "ablation_threshold_sensitivity_7class_main_paper.csv"
table_b_main.to_csv(table_b_main_path, index=False)

table_b_main

Empty DataFrame
Columns: [Model, Dataset, Threshold Pair, Accept (%), Defer (%), Reject (%), Accept Accuracy (%), Wrong Capture Rate (%)]
Index: []

In [57]:
def region_accuracy(df, region):
    region_df = df[df["decision_region"] == region]

    if len(region_df) == 0:
        return np.nan

    return region_df["correct"].mean() * 100


def compute_extended_decision_metrics(df, scheme_name, alpha=None, beta=None):
    total_samples = len(df)
    total_wrong = (~df["correct"]).sum()

    accept_df = df[df["decision_region"] == "Accept"]
    defer_df = df[df["decision_region"] == "Defer"]
    reject_df = df[df["decision_region"] == "Reject"]

    accept_percentage = len(accept_df) / total_samples * 100
    defer_percentage = len(defer_df) / total_samples * 100
    reject_percentage = len(reject_df) / total_samples * 100

    accept_accuracy = region_accuracy(df, "Accept")
    defer_accuracy = region_accuracy(df, "Defer")
    reject_accuracy = region_accuracy(df, "Reject")

    captured_wrong = df[
        (~df["correct"]) &
        (df["decision_region"].isin(["Defer", "Reject"]))
    ]

    if total_wrong > 0:
        wrong_capture_rate = len(captured_wrong) / total_wrong * 100
    else:
        wrong_capture_rate = np.nan

    return {
        "scheme": scheme_name,
        "alpha": alpha,
        "beta": beta,
        "accept_percentage": accept_percentage,
        "accept_accuracy": accept_accuracy,
        "defer_percentage": defer_percentage,
        "defer_accuracy": defer_accuracy,
        "reject_percentage": reject_percentage,
        "reject_accuracy": reject_accuracy,
        "wrong_capture_rate": wrong_capture_rate
    }

In [58]:
two_way_alphas = [0.85, 0.90, 0.95]

three_way_thresholds = [
    (0.95, 0.70),
    (0.90, 0.60),
    (0.85, 0.50)
]

extended_rows = []

group_cols = ["model", "dataset", "seed"]

for (model_name, dataset_name, seed), group_df in all_predictions_df.groupby(group_cols):
    group_df = group_df.copy()

    # Standard hard prediction
    standard_df = group_df.copy()
    standard_df["decision_region"] = "Accept"

    result = compute_extended_decision_metrics(
        standard_df,
        scheme_name="Standard",
        alpha=None,
        beta=None
    )
    result["model"] = model_name
    result["dataset"] = dataset_name
    result["seed"] = seed
    extended_rows.append(result)

    # Two-way decision
    for alpha in two_way_alphas:
        two_way_df = group_df.copy()
        two_way_df["decision_region"] = np.where(
            two_way_df["confidence"] >= alpha,
            "Accept",
            "Reject"
        )

        result = compute_extended_decision_metrics(
            two_way_df,
            scheme_name="Two-way",
            alpha=alpha,
            beta=None
        )
        result["model"] = model_name
        result["dataset"] = dataset_name
        result["seed"] = seed
        extended_rows.append(result)

    # Three-way decision
    for alpha, beta in three_way_thresholds:
        three_way_df = group_df.copy()

        conditions = [
            three_way_df["confidence"] >= alpha,
            (three_way_df["confidence"] >= beta) & (three_way_df["confidence"] < alpha),
            three_way_df["confidence"] < beta
        ]

        choices = ["Accept", "Defer", "Reject"]

        three_way_df["decision_region"] = np.select(
            conditions,
            choices,
            default="Reject"
        )

        result = compute_extended_decision_metrics(
            three_way_df,
            scheme_name="Three-way",
            alpha=alpha,
            beta=beta
        )
        result["model"] = model_name
        result["dataset"] = dataset_name
        result["seed"] = seed
        extended_rows.append(result)

extended_ablation_df = pd.DataFrame(extended_rows)

extended_ablation_path = "ablation_extended_region_metrics_per_seed.csv"
extended_ablation_df.to_csv(extended_ablation_path, index=False)

print("Saved:", extended_ablation_path)
extended_ablation_df.head()

Saved: ablation_extended_region_metrics_per_seed.csv

,scheme,alpha,beta,accept_percentage,accept_accuracy,defer_percentage,defer_accuracy,reject_percentage,reject_accuracy,wrong_capture_rate,model,dataset,seed
0,Standard,NaN,NaN,100.000000,96.666667,0.0,NaN,0.000000,NaN,0.0,EfficientNetB0,finetuned_target_3class,42
1,Two-way,0.85,NaN,96.666667,99.310345,0.0,NaN,3.333333,20.000000,80.0,EfficientNetB0,finetuned_target_3class,42
2,Two-way,0.90,NaN,96.000000,99.305556,0.0,NaN,4.000000,33.333333,80.0,EfficientNetB0,finetuned_target_3class,42
3,Two-way,0.95,NaN,93.333333,100.000000,0.0,NaN,6.666667,50.000000,100.0,EfficientNetB0,finetuned_target_3class,42
4,Three-way,0.95,0.7,93.333333,100.000000,4.0,83.333333,2.666667,0.000000,100.0,EfficientNetB0,finetuned_target_3class,42

In [60]:
main_table_df = extended_ablation_df[
    (
        (extended_ablation_df["scheme"] == "Standard") |
        (
            (extended_ablation_df["scheme"] == "Two-way") &
            (extended_ablation_df["alpha"] == 0.90)
        ) |
        (
            (extended_ablation_df["scheme"] == "Three-way") &
            (extended_ablation_df["alpha"] == 0.90) &
            (extended_ablation_df["beta"] == 0.60)
        )
    )
].copy()

In [61]:
summary_metrics = [
    "accept_percentage",
    "accept_accuracy",
    "defer_percentage",
    "defer_accuracy",
    "reject_percentage",
    "reject_accuracy",
    "wrong_capture_rate"
]

summary_rows = []

for keys, group in main_table_df.groupby(["model", "dataset", "scheme", "alpha", "beta"], dropna=False):
    model_name, dataset_name, scheme, alpha, beta = keys

    row = {
        "model": model_name,
        "dataset": dataset_name,
        "scheme": scheme,
        "alpha": alpha,
        "beta": beta
    }

    for metric in summary_metrics:
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_std"] = group[metric].std(ddof=0)

    summary_rows.append(row)

main_summary_df = pd.DataFrame(summary_rows)

In [62]:
def fmt_mean_std(row, metric):
    mean_value = row[f"{metric}_mean"]
    std_value = row[f"{metric}_std"]

    if pd.isna(mean_value):
        return "-"

    return f"{mean_value:.2f} ± {std_value:.2f}"


def decision_label(row):
    if row["scheme"] == "Standard":
        return "Standard"
    elif row["scheme"] == "Two-way":
        return "Two-way α=0.90"
    else:
        return "Three-way α=0.90, β=0.60"


paper_extended_table = pd.DataFrame({
    "Model": main_summary_df["model"],
    "Dataset": main_summary_df["dataset"],
    "Decision": main_summary_df.apply(decision_label, axis=1),
    "Accept %": main_summary_df.apply(lambda row: fmt_mean_std(row, "accept_percentage"), axis=1),
    "Accept Acc.": main_summary_df.apply(lambda row: fmt_mean_std(row, "accept_accuracy"), axis=1),
    "Defer %": main_summary_df.apply(lambda row: fmt_mean_std(row, "defer_percentage"), axis=1),
    "Defer Acc.": main_summary_df.apply(lambda row: fmt_mean_std(row, "defer_accuracy"), axis=1),
    "Reject %": main_summary_df.apply(lambda row: fmt_mean_std(row, "reject_percentage"), axis=1),
    "Reject Acc.": main_summary_df.apply(lambda row: fmt_mean_std(row, "reject_accuracy"), axis=1),
    "WCR": main_summary_df.apply(lambda row: fmt_mean_std(row, "wrong_capture_rate"), axis=1)
})

paper_extended_table = paper_extended_table.sort_values(["Dataset", "Model", "Decision"])

paper_extended_table_path = "ablation_main_paper_extended_region_table.csv"
paper_extended_table.to_csv(paper_extended_table_path, index=False)

print("Saved:", paper_extended_table_path)
paper_extended_table

Saved: ablation_main_paper_extended_region_table.csv

,Model,Dataset,Decision,Accept %,Accept Acc.,Defer %,Defer Acc.,Reject %,Reject Acc.,WCR
0,EfficientNetB0,finetuned_target_3class,Standard,100.00 ± 0.00,98.93 ± 1.16,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
1,EfficientNetB0,finetuned_target_3class,"Three-way α=0.90, β=0.60",95.87 ± 1.07,99.86 ± 0.28,3.20 ± 1.15,85.83 ± 13.33,0.93 ± 0.68,62.50 ± 41.46,95.00 ± 8.66
2,EfficientNetB0,finetuned_target_3class,Two-way α=0.90,95.87 ± 1.07,99.86 ± 0.28,0.00 ± 0.00,-,4.13 ± 1.07,76.11 ± 22.88,95.00 ± 8.66
9,Lightweight CNN,finetuned_target_3class,Standard,100.00 ± 0.00,87.87 ± 2.54,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
10,Lightweight CNN,finetuned_target_3class,"Three-way α=0.90, β=0.60",51.47 ± 3.54,98.49 ± 1.46,37.60 ± 2.00,83.03 ± 3.75,10.93 ± 2.69,54.66 ± 15.93,93.64 ± 6.05
11,Lightweight CNN,finetuned_target_3class,Two-way α=0.90,51.47 ± 3.54,98.49 ± 1.46,0.00 ± 0.00,-,48.53 ± 3.54,76.56 ± 4.94,93.64 ± 6.05
18,MobileNetV2,finetuned_target_3class,Standard,100.00 ± 0.00,95.07 ± 3.09,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
19,MobileNetV2,finetuned_target_3class,"Three-way α=0.90, β=0.60",91.87 ± 3.80,97.77 ± 1.95,6.53 ± 3.80,73.88 ± 18.77,1.60 ± 1.08,51.67 ± 9.57,68.47 ± 20.80
20,MobileNetV2,finetuned_target_3class,Two-way α=0.90,91.87 ± 3.80,97.77 ± 1.95,0.00 ± 0.00,-,8.13 ± 3.80,66.76 ± 12.14,68.47 ± 20.80
3,EfficientNetB0,source_3class,Standard,100.00 ± 0.00,99.54 ± 0.41,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
4,EfficientNetB0,source_3class,"Three-way α=0.90, β=0.60",94.07 ± 1.15,99.90 ± 0.20,4.91 ± 0.95,93.48 ± 5.67,1.02 ± 0.68,90.00 ± 20.00,83.33 ± 23.57
5,EfficientNetB0,source_3class,Two-way α=0.90,94.07 ± 1.15,99.90 ± 0.20,0.00 ± 0.00,-,5.93 ± 1.15,93.10 ± 5.87,83.33 ± 23.57
12,Lightweight CNN,source_3class,Standard,100.00 ± 0.00,89.81 ± 2.38,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
13,Lightweight CNN,source_3class,"Three-way α=0.90, β=0.60",51.85 ± 9.32,99.00 ± 0.90,37.78 ± 8.40,86.35 ± 5.28,10.37 ± 1.26,53.59 ± 9.99,95.17 ± 4.79
14,Lightweight CNN,source_3class,Two-way α=0.90,51.85 ± 9.32,99.00 ± 0.90,0.00 ± 0.00,-,48.15 ± 9.32,79.13 ± 5.65,95.17 ± 4.79
21,MobileNetV2,source_3class,Standard,100.00 ± 0.00,98.52 ± 0.74,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
22,MobileNetV2,source_3class,"Three-way α=0.90, β=0.60",95.74 ± 1.03,99.51 ± 0.31,3.61 ± 0.90,81.11 ± 12.25,0.65 ± 0.23,60.00 ± 37.42,61.33 ± 33.57
23,MobileNetV2,source_3class,Two-way α=0.90,95.74 ± 1.03,99.51 ± 0.31,0.00 ± 0.00,-,4.26 ± 1.03,76.97 ± 13.08,61.33 ± 33.57
6,EfficientNetB0,zero_shot_target_3class,Standard,100.00 ± 0.00,91.73 ± 1.16,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
7,EfficientNetB0,zero_shot_target_3class,"Three-way α=0.90, β=0.60",75.20 ± 2.17,99.82 ± 0.36,13.73 ± 0.68,79.88 ± 7.46,11.07 ± 1.61,49.91 ± 14.02,98.67 ± 2.67
8,EfficientNetB0,zero_shot_target_3class,Two-way α=0.90,75.20 ± 2.17,99.82 ± 0.36,0.00 ± 0.00,-,24.80 ± 2.17,67.20 ± 2.70,98.67 ± 2.67
15,Lightweight CNN,zero_shot_target_3class,Standard,100.00 ± 0.00,65.87 ± 6.67,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
16,Lightweight CNN,zero_shot_target_3class,"Three-way α=0.90, β=0.60",39.33 ± 9.27,78.64 ± 11.15,46.93 ± 5.81,58.89 ± 7.11,13.73 ± 4.31,57.92 ± 6.29,74.72 ± 12.17
17,Lightweight CNN,zero_shot_target_3class,Two-way α=0.90,39.33 ± 9.27,78.64 ± 11.15,0.00 ± 0.00,-,60.67 ± 9.27,58.31 ± 6.18,74.72 ± 12.17
24,MobileNetV2,zero_shot_target_3class,Standard,100.00 ± 0.00,85.73 ± 3.47,0.00 ± 0.00,-,0.00 ± 0.00,-,0.00 ± 0.00
25,MobileNetV2,zero_shot_target_3class,"Three-way α=0.90, β=0.60",77.33 ± 4.17,96.72 ± 1.03,14.40 ± 3.69,53.53 ± 16.27,8.27 ± 1.87,34.59 ± 7.50,82.33 ± 3.45
26,MobileNetV2,zero_shot_target_3class,Two-way α=0.90,77.33 ± 4.17,96.72 ± 1.03,0.00 ± 0.00,-,22.67 ± 4.17,47.52 ± 11.29,82.33 ± 3.45

In [63]:
gap_source_df = extended_ablation_df[
    (extended_ablation_df["scheme"] == "Three-way") &
    (extended_ablation_df["alpha"] == 0.90) &
    (extended_ablation_df["beta"] == 0.60)
].copy()

gap_metrics = [
    "accept_accuracy",
    "defer_accuracy",
    "reject_accuracy"
]

gap_summary_rows = []

for keys, group in gap_source_df.groupby(["model", "dataset"]):
    model_name, dataset_name = keys

    accept_mean = group["accept_accuracy"].mean()
    accept_std = group["accept_accuracy"].std(ddof=0)

    defer_mean = group["defer_accuracy"].mean()
    defer_std = group["defer_accuracy"].std(ddof=0)

    reject_mean = group["reject_accuracy"].mean()
    reject_std = group["reject_accuracy"].std(ddof=0)

    gap_ad = accept_mean - defer_mean
    gap_dr = defer_mean - reject_mean

    gap_summary_rows.append({
        "Model": model_name,
        "Dataset": dataset_name,
        "Accept Acc. Mean": accept_mean,
        "Accept Acc. Std": accept_std,
        "Defer Acc. Mean": defer_mean,
        "Defer Acc. Std": defer_std,
        "Reject Acc. Mean": reject_mean,
        "Reject Acc. Std": reject_std,
        "Gap(A,D)": gap_ad,
        "Gap(D,R)": gap_dr
    })

gap_table_raw = pd.DataFrame(gap_summary_rows)

In [64]:
def fmt_acc(mean_value, std_value):
    if pd.isna(mean_value):
        return "-"

    return f"{mean_value:.2f} ± {std_value:.2f}"


def fmt_gap(value):
    if pd.isna(value):
        return "-"

    return f"{value:.2f}"


gap_table = pd.DataFrame({
    "Model": gap_table_raw["Model"],
    "Dataset": gap_table_raw["Dataset"],
    "Accept Acc.": gap_table_raw.apply(
        lambda row: fmt_acc(row["Accept Acc. Mean"], row["Accept Acc. Std"]),
        axis=1
    ),
    "Defer Acc.": gap_table_raw.apply(
        lambda row: fmt_acc(row["Defer Acc. Mean"], row["Defer Acc. Std"]),
        axis=1
    ),
    "Reject Acc.": gap_table_raw.apply(
        lambda row: fmt_acc(row["Reject Acc. Mean"], row["Reject Acc. Std"]),
        axis=1
    ),
    "Gap(A,D)": gap_table_raw["Gap(A,D)"].apply(fmt_gap),
    "Gap(D,R)": gap_table_raw["Gap(D,R)"].apply(fmt_gap)
})

gap_table = gap_table.sort_values(["Dataset", "Model"])

gap_table_path = "ablation_three_way_region_accuracy_gap_table.csv"
gap_table.to_csv(gap_table_path, index=False)

print("Saved:", gap_table_path)
gap_table

Saved: ablation_three_way_region_accuracy_gap_table.csv

,Model,Dataset,Accept Acc.,Defer Acc.,Reject Acc.,"Gap(A,D)","Gap(D,R)"
0,EfficientNetB0,finetuned_target_3class,99.86 ± 0.28,85.83 ± 13.33,62.50 ± 41.46,14.03,23.33
3,Lightweight CNN,finetuned_target_3class,98.49 ± 1.46,83.03 ± 3.75,54.66 ± 15.93,15.45,28.37
6,MobileNetV2,finetuned_target_3class,97.77 ± 1.95,73.88 ± 18.77,51.67 ± 9.57,23.89,22.21
1,EfficientNetB0,source_3class,99.90 ± 0.20,93.48 ± 5.67,90.00 ± 20.00,6.43,3.48
4,Lightweight CNN,source_3class,99.00 ± 0.90,86.35 ± 5.28,53.59 ± 9.99,12.64,32.76
7,MobileNetV2,source_3class,99.51 ± 0.31,81.11 ± 12.25,60.00 ± 37.42,18.40,21.11
2,EfficientNetB0,zero_shot_target_3class,99.82 ± 0.36,79.88 ± 7.46,49.91 ± 14.02,19.94,29.97
5,Lightweight CNN,zero_shot_target_3class,78.64 ± 11.15,58.89 ± 7.11,57.92 ± 6.29,19.74,0.97
8,MobileNetV2,zero_shot_target_3class,96.72 ± 1.03,53.53 ± 16.27,34.59 ± 7.50,43.19,18.94

In [65]:
for _, row in gap_table_raw.sort_values(["Dataset", "Model"]).iterrows():
    print(
        f"{row['Model']} | {row['Dataset']}: "
        f"Gap(A,D) = {row['Accept Acc. Mean']:.2f} - {row['Defer Acc. Mean']:.2f} = {row['Gap(A,D)']:.2f}; "
        f"Gap(D,R) = {row['Defer Acc. Mean']:.2f} - {row['Reject Acc. Mean']:.2f} = {row['Gap(D,R)']:.2f}"
    )

EfficientNetB0 | finetuned_target_3class: Gap(A,D) = 99.86 - 85.83 = 14.03; Gap(D,R) = 85.83 - 62.50 = 23.33
Lightweight CNN | finetuned_target_3class: Gap(A,D) = 98.49 - 83.03 = 15.45; Gap(D,R) = 83.03 - 54.66 = 28.37
MobileNetV2 | finetuned_target_3class: Gap(A,D) = 97.77 - 73.88 = 23.89; Gap(D,R) = 73.88 - 51.67 = 22.21
EfficientNetB0 | source_3class: Gap(A,D) = 99.90 - 93.48 = 6.43; Gap(D,R) = 93.48 - 90.00 = 3.48
Lightweight CNN | source_3class: Gap(A,D) = 99.00 - 86.35 = 12.64; Gap(D,R) = 86.35 - 53.59 = 32.76
MobileNetV2 | source_3class: Gap(A,D) = 99.51 - 81.11 = 18.40; Gap(D,R) = 81.11 - 60.00 = 21.11
EfficientNetB0 | zero_shot_target_3class: Gap(A,D) = 99.82 - 79.88 = 19.94; Gap(D,R) = 79.88 - 49.91 = 29.97
Lightweight CNN | zero_shot_target_3class: Gap(A,D) = 78.64 - 58.89 = 19.74; Gap(D,R) = 58.89 - 57.92 = 0.97
MobileNetV2 | zero_shot_target_3class: Gap(A,D) = 96.72 - 53.53 = 43.19; Gap(D,R) = 53.53 - 34.59 = 18.94

In [66]:
FINAL_EXPORT_NAME = "ICDM_final_all_experiments_outputs"

items_to_export = []

candidate_folders = [
    "models",
    "history",
    "histories",
    "reports",
    "prediction_csvs",
    "cross_dataset_transfer_20260530-210441"
]

for folder in candidate_folders:
    if os.path.exists(folder):
        items_to_export.append(folder)

for item in os.listdir("/kaggle/working"):
    if item.startswith("gradcam_") and os.path.isdir(item):
        items_to_export.append(item)

for item in os.listdir("/kaggle/working"):
    if item.endswith((".csv", ".png", ".json", ".pkl", ".keras")):
        items_to_export.append(item)

# Explicitly include all ablation files anywhere under /kaggle/working
for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if "ablation" in file.lower():
            rel_path = os.path.relpath(os.path.join(root, file), "/kaggle/working")
            items_to_export.append(rel_path)

items_to_export = list(dict.fromkeys(items_to_export))

print("Items to export:")
for item in items_to_export:
    print(item)

zip_name = f"{FINAL_EXPORT_NAME}.zip"

!zip -r {zip_name} {' '.join(items_to_export)}

print("Created final export:", zip_name)

Items to export:
cross_dataset_transfer_20260530-210441
ablation_extended_region_metrics_per_seed.csv
ablation_table_A_standard_two_way_three_way.csv
ablation_decision_mechanism_summary_mean_std.csv
ablation_main_paper_extended_region_table.csv
ablation_threshold_sensitivity_7class_main_paper.csv
ablation_threshold_sensitivity_results.csv
ablation_decision_mechanism_results.csv
ablation_three_way_region_accuracy_gap_table.csv
ablation_decision_mechanism_outputs.zip
  adding: cross_dataset_transfer_20260530-210441/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_per_seed_results.csv (deflated 77%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_42.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_777.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_3407.csv (deflated 82%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_777.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_777.csv (deflated 82%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_2024.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_42.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_42.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_2024.csv (deflated 82%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_2024.csv (deflated 82%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_3407.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_123.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_42.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_777.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_42.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_2024.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_777.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_2024.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_3407.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_3407.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_123.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_2024.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_3407.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_123.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_123.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_777.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_123.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_777.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_3407.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_zero_shot_target_3class_seed_123.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_42.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_source_3class_seed_42.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_123.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_777.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_source_3class_seed_42.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_777.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_MobileNetV2_finetuned_target_3class_seed_2024.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_123.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_123.csv (deflated 81%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_42.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_finetuned_target_3class_seed_2024.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_zero_shot_target_3class_seed_3407.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_source_3class_seed_3407.csv (deflated 82%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_Lightweight_CNN_zero_shot_target_3class_seed_3407.csv (deflated 91%)
  adding: cross_dataset_transfer_20260530-210441/prediction_csvs/test_predictions_EfficientNetB0_finetuned_target_3class_seed_2024.csv (deflated 92%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_paper_table.csv (deflated 46%)
  adding: cross_dataset_transfer_20260530-210441/histories/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_target_finetune_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_target_finetune_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_2024_source_history.pkl (deflated 50%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_123_target_finetune_history.pkl (deflated 64%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_source_history.pkl (deflated 50%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_source_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_target_finetune_history.pkl (deflated 61%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_42_target_finetune_history.pkl (deflated 44%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_123_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_123_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_source_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_42_target_finetune_history.pkl (deflated 60%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_42_target_finetune_history.pkl (deflated 58%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_777_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_3407_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_3407_target_finetune_history.pkl (deflated 51%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_777_source_history.pkl (deflated 56%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_2024_target_finetune_history.pkl (deflated 45%)
  adding: cross_dataset_transfer_20260530-210441/histories/EfficientNetB0_seed_2024_target_finetune_history.pkl (deflated 62%)
  adding: cross_dataset_transfer_20260530-210441/histories/MobileNetV2_seed_3407_source_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/histories/Lightweight_CNN_seed_777_target_finetune_history.pkl (deflated 57%)
  adding: cross_dataset_transfer_20260530-210441/cross_dataset_transfer_results.csv (deflated 59%)
  adding: cross_dataset_transfer_20260530-210441/models/ (stored 0%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_source.keras (deflated 14%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_3407_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_source.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_777_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_source.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_123_target_finetuned.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_123_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_42_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_3407_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_123_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_42_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_3407_source.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_42_target_finetuned.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_2024_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/EfficientNetB0_seed_2024_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_target_finetuned.keras (deflated 12%)
  adding: cross_dataset_transfer_20260530-210441/models/Lightweight_CNN_seed_777_source.keras (deflated 13%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_777_source.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/models/MobileNetV2_seed_2024_target_finetuned.keras (deflated 10%)
  adding: cross_dataset_transfer_20260530-210441/reports/ (stored 0%)
  adding: ablation_extended_region_metrics_per_seed.csv (deflated 86%)
  adding: ablation_table_A_standard_two_way_three_way.csv (deflated 77%)
  adding: ablation_decision_mechanism_summary_mean_std.csv (deflated 77%)
  adding: ablation_main_paper_extended_region_table.csv (deflated 75%)
  adding: ablation_threshold_sensitivity_7class_main_paper.csv (deflated 16%)
  adding: ablation_threshold_sensitivity_results.csv (deflated 70%)
  adding: ablation_decision_mechanism_results.csv (deflated 87%)
  adding: ablation_three_way_region_accuracy_gap_table.csv (deflated 52%)
  adding: ablation_decision_mechanism_outputs.zip (stored 0%)
Created final export: ICDM_final_all_experiments_outputs.zip

In [ ]:
SOURCE_DATASET_DIR = "/kaggle/input/datasets/faysalmiah1721758/potato-dataset"
TARGET_DATASET_DIR = "/kaggle/input/datasets/shahadhossin567r7455/potato-leaf-disease-dataset/Potato Leaf DIsease"